/**
 * generated by Xtext 2.16.0
 */
package xtext.pycom.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import xtext.pycom.ModuleName;
import xtext.pycom.ModuleType;
import xtext.pycom.Pin;
import xtext.pycom.PycomPackage;
import xtext.pycom.Sensor;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Sensor</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link xtext.pycom.impl.SensorImpl#getTypeName <em>Type Name</em>}</li>
 *   <li>{@link xtext.pycom.impl.SensorImpl#getSensorName <em>Sensor Name</em>}</li>
 *   <li>{@link xtext.pycom.impl.SensorImpl#getPins <em>Pins</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SensorImpl extends MinimalEObjectImpl.Container implements Sensor
{
  /**
   * The cached value of the '{@link #getTypeName() <em>Type Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTypeName()
   * @generated
   * @ordered
   */
  protected ModuleType typeName;

  /**
   * The cached value of the '{@link #getSensorName() <em>Sensor Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSensorName()
   * @generated
   * @ordered
   */
  protected ModuleName sensorName;

  /**
   * The cached value of the '{@link #getPins() <em>Pins</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPins()
   * @generated
   * @ordered
   */
  protected Pin pins;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SensorImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PycomPackage.Literals.SENSOR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ModuleType getTypeName()
  {
    return typeName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTypeName(ModuleType newTypeName, NotificationChain msgs)
  {
    ModuleType oldTypeName = typeName;
    typeName = newTypeName;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PycomPackage.SENSOR__TYPE_NAME, oldTypeName, newTypeName);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTypeName(ModuleType newTypeName)
  {
    if (newTypeName != typeName)
    {
      NotificationChain msgs = null;
      if (typeName != null)
        msgs = ((InternalEObject)typeName).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PycomPackage.SENSOR__TYPE_NAME, null, msgs);
      if (newTypeName != null)
        msgs = ((InternalEObject)newTypeName).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PycomPackage.SENSOR__TYPE_NAME, null, msgs);
      msgs = basicSetTypeName(newTypeName, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PycomPackage.SENSOR__TYPE_NAME, newTypeName, newTypeName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ModuleName getSensorName()
  {
    return sensorName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSensorName(ModuleName newSensorName, NotificationChain msgs)
  {
    ModuleName oldSensorName = sensorName;
    sensorName = newSensorName;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PycomPackage.SENSOR__SENSOR_NAME, oldSensorName, newSensorName);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSensorName(ModuleName newSensorName)
  {
    if (newSensorName != sensorName)
    {
      NotificationChain msgs = null;
      if (sensorName != null)
        msgs = ((InternalEObject)sensorName).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PycomPackage.SENSOR__SENSOR_NAME, null, msgs);
      if (newSensorName != null)
        msgs = ((InternalEObject)newSensorName).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PycomPackage.SENSOR__SENSOR_NAME, null, msgs);
      msgs = basicSetSensorName(newSensorName, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PycomPackage.SENSOR__SENSOR_NAME, newSensorName, newSensorName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Pin getPins()
  {
    return pins;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPins(Pin newPins, NotificationChain msgs)
  {
    Pin oldPins = pins;
    pins = newPins;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PycomPackage.SENSOR__PINS, oldPins, newPins);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPins(Pin newPins)
  {
    if (newPins != pins)
    {
      NotificationChain msgs = null;
      if (pins != null)
        msgs = ((InternalEObject)pins).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PycomPackage.SENSOR__PINS, null, msgs);
      if (newPins != null)
        msgs = ((InternalEObject)newPins).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PycomPackage.SENSOR__PINS, null, msgs);
      msgs = basicSetPins(newPins, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PycomPackage.SENSOR__PINS, newPins, newPins));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PycomPackage.SENSOR__TYPE_NAME:
        return basicSetTypeName(null, msgs);
      case PycomPackage.SENSOR__SENSOR_NAME:
        return basicSetSensorName(null, msgs);
      case PycomPackage.SENSOR__PINS:
        return basicSetPins(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PycomPackage.SENSOR__TYPE_NAME:
        return getTypeName();
      case PycomPackage.SENSOR__SENSOR_NAME:
        return getSensorName();
      case PycomPackage.SENSOR__PINS:
        return getPins();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PycomPackage.SENSOR__TYPE_NAME:
        setTypeName((ModuleType)newValue);
        return;
      case PycomPackage.SENSOR__SENSOR_NAME:
        setSensorName((ModuleName)newValue);
        return;
      case PycomPackage.SENSOR__PINS:
        setPins((Pin)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PycomPackage.SENSOR__TYPE_NAME:
        setTypeName((ModuleType)null);
        return;
      case PycomPackage.SENSOR__SENSOR_NAME:
        setSensorName((ModuleName)null);
        return;
      case PycomPackage.SENSOR__PINS:
        setPins((Pin)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PycomPackage.SENSOR__TYPE_NAME:
        return typeName != null;
      case PycomPackage.SENSOR__SENSOR_NAME:
        return sensorName != null;
      case PycomPackage.SENSOR__PINS:
        return pins != null;
    }
    return super.eIsSet(featureID);
  }

} //SensorImpl
