/**
 * generated by Xtext 2.16.0
 */
package xtext.scoping;

import com.google.common.base.Objects;
import java.util.ArrayList;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;
import xtext.pycom.Board;
import xtext.pycom.Function;
import xtext.pycom.Import;
import xtext.pycom.Library;
import xtext.pycom.PycomPackage;
import xtext.scoping.AbstractPycomScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class PycomScopeProvider extends AbstractPycomScopeProvider {
  @Override
  public IScope getScope(final EObject context, final EReference reference) {
    if (((context instanceof Function) && Objects.equal(reference, PycomPackage.Literals.FUNCTION__FUNCTION_NAME))) {
      final Board board = ((Function) context).getBoard();
      ArrayList<Import> candidates = new ArrayList<Import>();
      EList<Library> _library = board.getLibrary();
      for (final Library library : _library) {
        EList<Import> _imports = library.getImports();
        for (final Import import_ : _imports) {
          candidates.add(import_);
        }
      }
      return Scopes.scopeFor(candidates);
    }
    return super.getScope(context, reference);
  }
}
