/**
 * generated by Xtext 2.16.0
 */
package xtext.pycom;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Actuator</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.pycom.Actuator#getTypeName <em>Type Name</em>}</li>
 *   <li>{@link xtext.pycom.Actuator#getActuatorName <em>Actuator Name</em>}</li>
 *   <li>{@link xtext.pycom.Actuator#getPins <em>Pins</em>}</li>
 * </ul>
 *
 * @see xtext.pycom.PycomPackage#getActuator()
 * @model
 * @generated
 */
public interface Actuator extends BoardMember
{
  /**
   * Returns the value of the '<em><b>Type Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type Name</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Name</em>' containment reference.
   * @see #setTypeName(ModuleType)
   * @see xtext.pycom.PycomPackage#getActuator_TypeName()
   * @model containment="true"
   * @generated
   */
  ModuleType getTypeName();

  /**
   * Sets the value of the '{@link xtext.pycom.Actuator#getTypeName <em>Type Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type Name</em>' containment reference.
   * @see #getTypeName()
   * @generated
   */
  void setTypeName(ModuleType value);

  /**
   * Returns the value of the '<em><b>Actuator Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Actuator Name</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actuator Name</em>' containment reference.
   * @see #setActuatorName(ModuleName)
   * @see xtext.pycom.PycomPackage#getActuator_ActuatorName()
   * @model containment="true"
   * @generated
   */
  ModuleName getActuatorName();

  /**
   * Sets the value of the '{@link xtext.pycom.Actuator#getActuatorName <em>Actuator Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Actuator Name</em>' containment reference.
   * @see #getActuatorName()
   * @generated
   */
  void setActuatorName(ModuleName value);

  /**
   * Returns the value of the '<em><b>Pins</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pins</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pins</em>' containment reference.
   * @see #setPins(Pin)
   * @see xtext.pycom.PycomPackage#getActuator_Pins()
   * @model containment="true"
   * @generated
   */
  Pin getPins();

  /**
   * Sets the value of the '{@link xtext.pycom.Actuator#getPins <em>Pins</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pins</em>' containment reference.
   * @see #getPins()
   * @generated
   */
  void setPins(Pin value);

} // Actuator
