/**
 * generated by Xtext 2.16.0
 */
package xtext.pycom;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Board Member</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.pycom.BoardMember#getBoardMember <em>Board Member</em>}</li>
 * </ul>
 *
 * @see xtext.pycom.PycomPackage#getBoardMember()
 * @model
 * @generated
 */
public interface BoardMember extends EObject
{
  /**
   * Returns the value of the '<em><b>Board Member</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Board Member</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Board Member</em>' containment reference.
   * @see #setBoardMember(Sensor)
   * @see xtext.pycom.PycomPackage#getBoardMember_BoardMember()
   * @model containment="true"
   * @generated
   */
  Sensor getBoardMember();

  /**
   * Sets the value of the '{@link xtext.pycom.BoardMember#getBoardMember <em>Board Member</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Board Member</em>' containment reference.
   * @see #getBoardMember()
   * @generated
   */
  void setBoardMember(Sensor value);

} // BoardMember
