/**
 * generated by Xtext 2.16.0
 */
package xtext.pycom;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Connection</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.pycom.Connection#getHost <em>Host</em>}</li>
 *   <li>{@link xtext.pycom.Connection#getPortnumber <em>Portnumber</em>}</li>
 * </ul>
 *
 * @see xtext.pycom.PycomPackage#getConnection()
 * @model
 * @generated
 */
public interface Connection extends EObject
{
  /**
   * Returns the value of the '<em><b>Host</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Host</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Host</em>' containment reference.
   * @see #setHost(Host)
   * @see xtext.pycom.PycomPackage#getConnection_Host()
   * @model containment="true"
   * @generated
   */
  Host getHost();

  /**
   * Sets the value of the '{@link xtext.pycom.Connection#getHost <em>Host</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Host</em>' containment reference.
   * @see #getHost()
   * @generated
   */
  void setHost(Host value);

  /**
   * Returns the value of the '<em><b>Portnumber</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Portnumber</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Portnumber</em>' attribute.
   * @see #setPortnumber(int)
   * @see xtext.pycom.PycomPackage#getConnection_Portnumber()
   * @model
   * @generated
   */
  int getPortnumber();

  /**
   * Sets the value of the '{@link xtext.pycom.Connection#getPortnumber <em>Portnumber</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Portnumber</em>' attribute.
   * @see #getPortnumber()
   * @generated
   */
  void setPortnumber(int value);

} // Connection
