/**
 * generated by Xtext 2.16.0
 */
package xtext.pycom;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.pycom.Function#getBoard <em>Board</em>}</li>
 *   <li>{@link xtext.pycom.Function#getFunctionName <em>Function Name</em>}</li>
 *   <li>{@link xtext.pycom.Function#getPins <em>Pins</em>}</li>
 * </ul>
 *
 * @see xtext.pycom.PycomPackage#getFunction()
 * @model
 * @generated
 */
public interface Function extends ExpMember
{
  /**
   * Returns the value of the '<em><b>Board</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Board</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Board</em>' reference.
   * @see #setBoard(Board)
   * @see xtext.pycom.PycomPackage#getFunction_Board()
   * @model
   * @generated
   */
  Board getBoard();

  /**
   * Sets the value of the '{@link xtext.pycom.Function#getBoard <em>Board</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Board</em>' reference.
   * @see #getBoard()
   * @generated
   */
  void setBoard(Board value);

  /**
   * Returns the value of the '<em><b>Function Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Function Name</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function Name</em>' reference.
   * @see #setFunctionName(Import)
   * @see xtext.pycom.PycomPackage#getFunction_FunctionName()
   * @model
   * @generated
   */
  Import getFunctionName();

  /**
   * Sets the value of the '{@link xtext.pycom.Function#getFunctionName <em>Function Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Function Name</em>' reference.
   * @see #getFunctionName()
   * @generated
   */
  void setFunctionName(Import value);

  /**
   * Returns the value of the '<em><b>Pins</b></em>' containment reference list.
   * The list contents are of type {@link xtext.pycom.Pin}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pins</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pins</em>' containment reference list.
   * @see xtext.pycom.PycomPackage#getFunction_Pins()
   * @model containment="true"
   * @generated
   */
  EList<Pin> getPins();

} // Function
