/**
 * generated by Xtext 2.16.0
 */
package xtext.pycom;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Host</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.pycom.Host#getIpAdr <em>Ip Adr</em>}</li>
 *   <li>{@link xtext.pycom.Host#getWebsite <em>Website</em>}</li>
 * </ul>
 *
 * @see xtext.pycom.PycomPackage#getHost()
 * @model
 * @generated
 */
public interface Host extends EObject
{
  /**
   * Returns the value of the '<em><b>Ip Adr</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ip Adr</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ip Adr</em>' attribute.
   * @see #setIpAdr(String)
   * @see xtext.pycom.PycomPackage#getHost_IpAdr()
   * @model
   * @generated
   */
  String getIpAdr();

  /**
   * Sets the value of the '{@link xtext.pycom.Host#getIpAdr <em>Ip Adr</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ip Adr</em>' attribute.
   * @see #getIpAdr()
   * @generated
   */
  void setIpAdr(String value);

  /**
   * Returns the value of the '<em><b>Website</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Website</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Website</em>' attribute.
   * @see #setWebsite(String)
   * @see xtext.pycom.PycomPackage#getHost_Website()
   * @model
   * @generated
   */
  String getWebsite();

  /**
   * Sets the value of the '{@link xtext.pycom.Host#getWebsite <em>Website</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Website</em>' attribute.
   * @see #getWebsite()
   * @generated
   */
  void setWebsite(String value);

} // Host
