/**
 * generated by Xtext 2.16.0
 */
package xtext.pycom;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parameter Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.pycom.ParameterType#getNumber <em>Number</em>}</li>
 *   <li>{@link xtext.pycom.ParameterType#getText <em>Text</em>}</li>
 * </ul>
 *
 * @see xtext.pycom.PycomPackage#getParameterType()
 * @model
 * @generated
 */
public interface ParameterType extends EObject
{
  /**
   * Returns the value of the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Number</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Number</em>' attribute.
   * @see #setNumber(int)
   * @see xtext.pycom.PycomPackage#getParameterType_Number()
   * @model
   * @generated
   */
  int getNumber();

  /**
   * Sets the value of the '{@link xtext.pycom.ParameterType#getNumber <em>Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Number</em>' attribute.
   * @see #getNumber()
   * @generated
   */
  void setNumber(int value);

  /**
   * Returns the value of the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Text</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Text</em>' attribute.
   * @see #setText(String)
   * @see xtext.pycom.PycomPackage#getParameterType_Text()
   * @model
   * @generated
   */
  String getText();

  /**
   * Sets the value of the '{@link xtext.pycom.ParameterType#getText <em>Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Text</em>' attribute.
   * @see #getText()
   * @generated
   */
  void setText(String value);

} // ParameterType
