/**
 * generated by Xtext 2.16.0
 */
package xtext.pycom;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see xtext.pycom.PycomFactory
 * @model kind="package"
 * @generated
 */
public interface PycomPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "pycom";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.Pycom.xtext";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "pycom";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  PycomPackage eINSTANCE = xtext.pycom.impl.PycomPackageImpl.init();

  /**
   * The meta object id for the '{@link xtext.pycom.impl.SystemImpl <em>System</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.SystemImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getSystem()
   * @generated
   */
  int SYSTEM = 0;

  /**
   * The feature id for the '<em><b>Libraries</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__LIBRARIES = 0;

  /**
   * The feature id for the '<em><b>Imports</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__IMPORTS = 1;

  /**
   * The feature id for the '<em><b>Boards</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__BOARDS = 2;

  /**
   * The feature id for the '<em><b>Servers</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__SERVERS = 3;

  /**
   * The number of structural features of the '<em>System</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link xtext.pycom.impl.LibraryImpl <em>Library</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.LibraryImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getLibrary()
   * @generated
   */
  int LIBRARY = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIBRARY__NAME = 0;

  /**
   * The feature id for the '<em><b>Imports</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIBRARY__IMPORTS = 1;

  /**
   * The number of structural features of the '<em>Library</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIBRARY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link xtext.pycom.impl.ImportImpl <em>Import</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.ImportImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getImport()
   * @generated
   */
  int IMPORT = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT__NAME = 0;

  /**
   * The feature id for the '<em><b>Parameter</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT__PARAMETER = 1;

  /**
   * The feature id for the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT__PATH = 2;

  /**
   * The number of structural features of the '<em>Import</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link xtext.pycom.impl.ParameterTypeImpl <em>Parameter Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.ParameterTypeImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getParameterType()
   * @generated
   */
  int PARAMETER_TYPE = 3;

  /**
   * The feature id for the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_TYPE__NUMBER = 0;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_TYPE__TEXT = 1;

  /**
   * The number of structural features of the '<em>Parameter Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_TYPE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link xtext.pycom.impl.ServerImpl <em>Server</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.ServerImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getServer()
   * @generated
   */
  int SERVER = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVER__NAME = 0;

  /**
   * The feature id for the '<em><b>Conn</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVER__CONN = 1;

  /**
   * The feature id for the '<em><b>Exps</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVER__EXPS = 2;

  /**
   * The number of structural features of the '<em>Server</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVER_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link xtext.pycom.impl.ConnectionImpl <em>Connection</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.ConnectionImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getConnection()
   * @generated
   */
  int CONNECTION = 5;

  /**
   * The feature id for the '<em><b>Host</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECTION__HOST = 0;

  /**
   * The feature id for the '<em><b>Portnumber</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECTION__PORTNUMBER = 1;

  /**
   * The number of structural features of the '<em>Connection</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link xtext.pycom.impl.HostImpl <em>Host</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.HostImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getHost()
   * @generated
   */
  int HOST = 6;

  /**
   * The feature id for the '<em><b>Ip Adr</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HOST__IP_ADR = 0;

  /**
   * The feature id for the '<em><b>Website</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HOST__WEBSITE = 1;

  /**
   * The number of structural features of the '<em>Host</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HOST_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link xtext.pycom.impl.BoardImpl <em>Board</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.BoardImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getBoard()
   * @generated
   */
  int BOARD = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOARD__NAME = 0;

  /**
   * The feature id for the '<em><b>Board Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOARD__BOARD_TYPE = 1;

  /**
   * The feature id for the '<em><b>Communication Rate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOARD__COMMUNICATION_RATE = 2;

  /**
   * The feature id for the '<em><b>Library</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOARD__LIBRARY = 3;

  /**
   * The feature id for the '<em><b>Board Members</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOARD__BOARD_MEMBERS = 4;

  /**
   * The number of structural features of the '<em>Board</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOARD_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link xtext.pycom.impl.BoardMemberImpl <em>Board Member</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.BoardMemberImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getBoardMember()
   * @generated
   */
  int BOARD_MEMBER = 8;

  /**
   * The feature id for the '<em><b>Board Member</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOARD_MEMBER__BOARD_MEMBER = 0;

  /**
   * The number of structural features of the '<em>Board Member</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOARD_MEMBER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link xtext.pycom.impl.ExpMemberImpl <em>Exp Member</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.ExpMemberImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getExpMember()
   * @generated
   */
  int EXP_MEMBER = 10;

  /**
   * The number of structural features of the '<em>Exp Member</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP_MEMBER_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link xtext.pycom.impl.ConditionalActionImpl <em>Conditional Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.ConditionalActionImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getConditionalAction()
   * @generated
   */
  int CONDITIONAL_ACTION = 9;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONAL_ACTION__TYPE = EXP_MEMBER_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONAL_ACTION__CONDITION = EXP_MEMBER_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Exp Members</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONAL_ACTION__EXP_MEMBERS = EXP_MEMBER_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Conditional Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITIONAL_ACTION_FEATURE_COUNT = EXP_MEMBER_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link xtext.pycom.impl.SensorImpl <em>Sensor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.SensorImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getSensor()
   * @generated
   */
  int SENSOR = 11;

  /**
   * The feature id for the '<em><b>Type Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR__TYPE_NAME = 0;

  /**
   * The feature id for the '<em><b>Sensor Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR__SENSOR_NAME = 1;

  /**
   * The feature id for the '<em><b>Pins</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR__PINS = 2;

  /**
   * The number of structural features of the '<em>Sensor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link xtext.pycom.impl.ActuatorImpl <em>Actuator</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.ActuatorImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getActuator()
   * @generated
   */
  int ACTUATOR = 12;

  /**
   * The feature id for the '<em><b>Board Member</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTUATOR__BOARD_MEMBER = BOARD_MEMBER__BOARD_MEMBER;

  /**
   * The feature id for the '<em><b>Type Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTUATOR__TYPE_NAME = BOARD_MEMBER_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Actuator Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTUATOR__ACTUATOR_NAME = BOARD_MEMBER_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Pins</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTUATOR__PINS = BOARD_MEMBER_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Actuator</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTUATOR_FEATURE_COUNT = BOARD_MEMBER_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link xtext.pycom.impl.ModuleTypeImpl <em>Module Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.ModuleTypeImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getModuleType()
   * @generated
   */
  int MODULE_TYPE = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODULE_TYPE__NAME = 0;

  /**
   * The number of structural features of the '<em>Module Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODULE_TYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link xtext.pycom.impl.ModuleNameImpl <em>Module Name</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.ModuleNameImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getModuleName()
   * @generated
   */
  int MODULE_NAME = 14;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODULE_NAME__NAME = 0;

  /**
   * The number of structural features of the '<em>Module Name</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODULE_NAME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link xtext.pycom.impl.CommunicationImpl <em>Communication</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.CommunicationImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getCommunication()
   * @generated
   */
  int COMMUNICATION = 15;

  /**
   * The feature id for the '<em><b>Board Member</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMUNICATION__BOARD_MEMBER = BOARD_MEMBER__BOARD_MEMBER;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMUNICATION__TYPE = BOARD_MEMBER_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Communication</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMUNICATION_FEATURE_COUNT = BOARD_MEMBER_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link xtext.pycom.impl.CommunicationTypeImpl <em>Communication Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.CommunicationTypeImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getCommunicationType()
   * @generated
   */
  int COMMUNICATION_TYPE = 16;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMUNICATION_TYPE__NAME = 0;

  /**
   * The feature id for the '<em><b>Ssid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMUNICATION_TYPE__SSID = 1;

  /**
   * The feature id for the '<em><b>Password</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMUNICATION_TYPE__PASSWORD = 2;

  /**
   * The number of structural features of the '<em>Communication Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMUNICATION_TYPE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link xtext.pycom.impl.PinImpl <em>Pin</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.PinImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getPin()
   * @generated
   */
  int PIN = 17;

  /**
   * The feature id for the '<em><b>Power</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PIN__POWER = 0;

  /**
   * The feature id for the '<em><b>Input</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PIN__INPUT = 1;

  /**
   * The number of structural features of the '<em>Pin</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PIN_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link xtext.pycom.impl.PinNameImpl <em>Pin Name</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.PinNameImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getPinName()
   * @generated
   */
  int PIN_NAME = 18;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PIN_NAME__NAME = 0;

  /**
   * The number of structural features of the '<em>Pin Name</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PIN_NAME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link xtext.pycom.impl.ConditionImpl <em>Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.ConditionImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getCondition()
   * @generated
   */
  int CONDITION = 19;

  /**
   * The feature id for the '<em><b>Logic Ex</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__LOGIC_EX = 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__OPERATOR = 1;

  /**
   * The feature id for the '<em><b>Nested Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__NESTED_CONDITION = 2;

  /**
   * The number of structural features of the '<em>Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link xtext.pycom.impl.LogicExpImpl <em>Logic Exp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.LogicExpImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getLogicExp()
   * @generated
   */
  int LOGIC_EXP = 20;

  /**
   * The feature id for the '<em><b>Bool Val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGIC_EXP__BOOL_VAL = 0;

  /**
   * The feature id for the '<em><b>Comp Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGIC_EXP__COMP_EXP = 1;

  /**
   * The number of structural features of the '<em>Logic Exp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGIC_EXP_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link xtext.pycom.impl.BooleanImpl <em>Boolean</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.BooleanImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getBoolean()
   * @generated
   */
  int BOOLEAN = 21;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN__VALUE = 0;

  /**
   * The number of structural features of the '<em>Boolean</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link xtext.pycom.impl.ComparisonExpImpl <em>Comparison Exp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.ComparisonExpImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getComparisonExp()
   * @generated
   */
  int COMPARISON_EXP = 22;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON_EXP__LEFT = 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON_EXP__OP = 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON_EXP__RIGHT = 2;

  /**
   * The number of structural features of the '<em>Comparison Exp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARISON_EXP_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link xtext.pycom.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.ExpressionImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 23;

  /**
   * The feature id for the '<em><b>Output Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__OUTPUT_VALUE = 0;

  /**
   * The feature id for the '<em><b>Outputfunction</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__OUTPUTFUNCTION = 1;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link xtext.pycom.impl.FunctionImpl <em>Function</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xtext.pycom.impl.FunctionImpl
   * @see xtext.pycom.impl.PycomPackageImpl#getFunction()
   * @generated
   */
  int FUNCTION = 24;

  /**
   * The feature id for the '<em><b>Board</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__BOARD = EXP_MEMBER_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Function Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__FUNCTION_NAME = EXP_MEMBER_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Pins</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__PINS = EXP_MEMBER_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Function</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_FEATURE_COUNT = EXP_MEMBER_FEATURE_COUNT + 3;


  /**
   * Returns the meta object for class '{@link xtext.pycom.System <em>System</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>System</em>'.
   * @see xtext.pycom.System
   * @generated
   */
  EClass getSystem();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.pycom.System#getLibraries <em>Libraries</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Libraries</em>'.
   * @see xtext.pycom.System#getLibraries()
   * @see #getSystem()
   * @generated
   */
  EReference getSystem_Libraries();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.pycom.System#getImports <em>Imports</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Imports</em>'.
   * @see xtext.pycom.System#getImports()
   * @see #getSystem()
   * @generated
   */
  EReference getSystem_Imports();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.pycom.System#getBoards <em>Boards</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Boards</em>'.
   * @see xtext.pycom.System#getBoards()
   * @see #getSystem()
   * @generated
   */
  EReference getSystem_Boards();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.pycom.System#getServers <em>Servers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Servers</em>'.
   * @see xtext.pycom.System#getServers()
   * @see #getSystem()
   * @generated
   */
  EReference getSystem_Servers();

  /**
   * Returns the meta object for class '{@link xtext.pycom.Library <em>Library</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Library</em>'.
   * @see xtext.pycom.Library
   * @generated
   */
  EClass getLibrary();

  /**
   * Returns the meta object for the attribute '{@link xtext.pycom.Library#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xtext.pycom.Library#getName()
   * @see #getLibrary()
   * @generated
   */
  EAttribute getLibrary_Name();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.pycom.Library#getImports <em>Imports</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Imports</em>'.
   * @see xtext.pycom.Library#getImports()
   * @see #getLibrary()
   * @generated
   */
  EReference getLibrary_Imports();

  /**
   * Returns the meta object for class '{@link xtext.pycom.Import <em>Import</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Import</em>'.
   * @see xtext.pycom.Import
   * @generated
   */
  EClass getImport();

  /**
   * Returns the meta object for the attribute '{@link xtext.pycom.Import#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xtext.pycom.Import#getName()
   * @see #getImport()
   * @generated
   */
  EAttribute getImport_Name();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.pycom.Import#getParameter <em>Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parameter</em>'.
   * @see xtext.pycom.Import#getParameter()
   * @see #getImport()
   * @generated
   */
  EReference getImport_Parameter();

  /**
   * Returns the meta object for the attribute '{@link xtext.pycom.Import#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Path</em>'.
   * @see xtext.pycom.Import#getPath()
   * @see #getImport()
   * @generated
   */
  EAttribute getImport_Path();

  /**
   * Returns the meta object for class '{@link xtext.pycom.ParameterType <em>Parameter Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parameter Type</em>'.
   * @see xtext.pycom.ParameterType
   * @generated
   */
  EClass getParameterType();

  /**
   * Returns the meta object for the attribute '{@link xtext.pycom.ParameterType#getNumber <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Number</em>'.
   * @see xtext.pycom.ParameterType#getNumber()
   * @see #getParameterType()
   * @generated
   */
  EAttribute getParameterType_Number();

  /**
   * Returns the meta object for the attribute '{@link xtext.pycom.ParameterType#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see xtext.pycom.ParameterType#getText()
   * @see #getParameterType()
   * @generated
   */
  EAttribute getParameterType_Text();

  /**
   * Returns the meta object for class '{@link xtext.pycom.Server <em>Server</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Server</em>'.
   * @see xtext.pycom.Server
   * @generated
   */
  EClass getServer();

  /**
   * Returns the meta object for the attribute '{@link xtext.pycom.Server#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xtext.pycom.Server#getName()
   * @see #getServer()
   * @generated
   */
  EAttribute getServer_Name();

  /**
   * Returns the meta object for the containment reference '{@link xtext.pycom.Server#getConn <em>Conn</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Conn</em>'.
   * @see xtext.pycom.Server#getConn()
   * @see #getServer()
   * @generated
   */
  EReference getServer_Conn();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.pycom.Server#getExps <em>Exps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Exps</em>'.
   * @see xtext.pycom.Server#getExps()
   * @see #getServer()
   * @generated
   */
  EReference getServer_Exps();

  /**
   * Returns the meta object for class '{@link xtext.pycom.Connection <em>Connection</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Connection</em>'.
   * @see xtext.pycom.Connection
   * @generated
   */
  EClass getConnection();

  /**
   * Returns the meta object for the containment reference '{@link xtext.pycom.Connection#getHost <em>Host</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Host</em>'.
   * @see xtext.pycom.Connection#getHost()
   * @see #getConnection()
   * @generated
   */
  EReference getConnection_Host();

  /**
   * Returns the meta object for the attribute '{@link xtext.pycom.Connection#getPortnumber <em>Portnumber</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Portnumber</em>'.
   * @see xtext.pycom.Connection#getPortnumber()
   * @see #getConnection()
   * @generated
   */
  EAttribute getConnection_Portnumber();

  /**
   * Returns the meta object for class '{@link xtext.pycom.Host <em>Host</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Host</em>'.
   * @see xtext.pycom.Host
   * @generated
   */
  EClass getHost();

  /**
   * Returns the meta object for the attribute '{@link xtext.pycom.Host#getIpAdr <em>Ip Adr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ip Adr</em>'.
   * @see xtext.pycom.Host#getIpAdr()
   * @see #getHost()
   * @generated
   */
  EAttribute getHost_IpAdr();

  /**
   * Returns the meta object for the attribute '{@link xtext.pycom.Host#getWebsite <em>Website</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Website</em>'.
   * @see xtext.pycom.Host#getWebsite()
   * @see #getHost()
   * @generated
   */
  EAttribute getHost_Website();

  /**
   * Returns the meta object for class '{@link xtext.pycom.Board <em>Board</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Board</em>'.
   * @see xtext.pycom.Board
   * @generated
   */
  EClass getBoard();

  /**
   * Returns the meta object for the attribute '{@link xtext.pycom.Board#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xtext.pycom.Board#getName()
   * @see #getBoard()
   * @generated
   */
  EAttribute getBoard_Name();

  /**
   * Returns the meta object for the attribute '{@link xtext.pycom.Board#getBoardType <em>Board Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Board Type</em>'.
   * @see xtext.pycom.Board#getBoardType()
   * @see #getBoard()
   * @generated
   */
  EAttribute getBoard_BoardType();

  /**
   * Returns the meta object for the attribute '{@link xtext.pycom.Board#getCommunicationRate <em>Communication Rate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Communication Rate</em>'.
   * @see xtext.pycom.Board#getCommunicationRate()
   * @see #getBoard()
   * @generated
   */
  EAttribute getBoard_CommunicationRate();

  /**
   * Returns the meta object for the reference list '{@link xtext.pycom.Board#getLibrary <em>Library</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Library</em>'.
   * @see xtext.pycom.Board#getLibrary()
   * @see #getBoard()
   * @generated
   */
  EReference getBoard_Library();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.pycom.Board#getBoardMembers <em>Board Members</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Board Members</em>'.
   * @see xtext.pycom.Board#getBoardMembers()
   * @see #getBoard()
   * @generated
   */
  EReference getBoard_BoardMembers();

  /**
   * Returns the meta object for class '{@link xtext.pycom.BoardMember <em>Board Member</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Board Member</em>'.
   * @see xtext.pycom.BoardMember
   * @generated
   */
  EClass getBoardMember();

  /**
   * Returns the meta object for the containment reference '{@link xtext.pycom.BoardMember#getBoardMember <em>Board Member</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Board Member</em>'.
   * @see xtext.pycom.BoardMember#getBoardMember()
   * @see #getBoardMember()
   * @generated
   */
  EReference getBoardMember_BoardMember();

  /**
   * Returns the meta object for class '{@link xtext.pycom.ConditionalAction <em>Conditional Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Conditional Action</em>'.
   * @see xtext.pycom.ConditionalAction
   * @generated
   */
  EClass getConditionalAction();

  /**
   * Returns the meta object for the attribute '{@link xtext.pycom.ConditionalAction#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see xtext.pycom.ConditionalAction#getType()
   * @see #getConditionalAction()
   * @generated
   */
  EAttribute getConditionalAction_Type();

  /**
   * Returns the meta object for the containment reference '{@link xtext.pycom.ConditionalAction#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see xtext.pycom.ConditionalAction#getCondition()
   * @see #getConditionalAction()
   * @generated
   */
  EReference getConditionalAction_Condition();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.pycom.ConditionalAction#getExpMembers <em>Exp Members</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Exp Members</em>'.
   * @see xtext.pycom.ConditionalAction#getExpMembers()
   * @see #getConditionalAction()
   * @generated
   */
  EReference getConditionalAction_ExpMembers();

  /**
   * Returns the meta object for class '{@link xtext.pycom.ExpMember <em>Exp Member</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Exp Member</em>'.
   * @see xtext.pycom.ExpMember
   * @generated
   */
  EClass getExpMember();

  /**
   * Returns the meta object for class '{@link xtext.pycom.Sensor <em>Sensor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sensor</em>'.
   * @see xtext.pycom.Sensor
   * @generated
   */
  EClass getSensor();

  /**
   * Returns the meta object for the containment reference '{@link xtext.pycom.Sensor#getTypeName <em>Type Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type Name</em>'.
   * @see xtext.pycom.Sensor#getTypeName()
   * @see #getSensor()
   * @generated
   */
  EReference getSensor_TypeName();

  /**
   * Returns the meta object for the containment reference '{@link xtext.pycom.Sensor#getSensorName <em>Sensor Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Sensor Name</em>'.
   * @see xtext.pycom.Sensor#getSensorName()
   * @see #getSensor()
   * @generated
   */
  EReference getSensor_SensorName();

  /**
   * Returns the meta object for the containment reference '{@link xtext.pycom.Sensor#getPins <em>Pins</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Pins</em>'.
   * @see xtext.pycom.Sensor#getPins()
   * @see #getSensor()
   * @generated
   */
  EReference getSensor_Pins();

  /**
   * Returns the meta object for class '{@link xtext.pycom.Actuator <em>Actuator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Actuator</em>'.
   * @see xtext.pycom.Actuator
   * @generated
   */
  EClass getActuator();

  /**
   * Returns the meta object for the containment reference '{@link xtext.pycom.Actuator#getTypeName <em>Type Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type Name</em>'.
   * @see xtext.pycom.Actuator#getTypeName()
   * @see #getActuator()
   * @generated
   */
  EReference getActuator_TypeName();

  /**
   * Returns the meta object for the containment reference '{@link xtext.pycom.Actuator#getActuatorName <em>Actuator Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Actuator Name</em>'.
   * @see xtext.pycom.Actuator#getActuatorName()
   * @see #getActuator()
   * @generated
   */
  EReference getActuator_ActuatorName();

  /**
   * Returns the meta object for the containment reference '{@link xtext.pycom.Actuator#getPins <em>Pins</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Pins</em>'.
   * @see xtext.pycom.Actuator#getPins()
   * @see #getActuator()
   * @generated
   */
  EReference getActuator_Pins();

  /**
   * Returns the meta object for class '{@link xtext.pycom.ModuleType <em>Module Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Module Type</em>'.
   * @see xtext.pycom.ModuleType
   * @generated
   */
  EClass getModuleType();

  /**
   * Returns the meta object for the attribute '{@link xtext.pycom.ModuleType#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xtext.pycom.ModuleType#getName()
   * @see #getModuleType()
   * @generated
   */
  EAttribute getModuleType_Name();

  /**
   * Returns the meta object for class '{@link xtext.pycom.ModuleName <em>Module Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Module Name</em>'.
   * @see xtext.pycom.ModuleName
   * @generated
   */
  EClass getModuleName();

  /**
   * Returns the meta object for the attribute '{@link xtext.pycom.ModuleName#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xtext.pycom.ModuleName#getName()
   * @see #getModuleName()
   * @generated
   */
  EAttribute getModuleName_Name();

  /**
   * Returns the meta object for class '{@link xtext.pycom.Communication <em>Communication</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Communication</em>'.
   * @see xtext.pycom.Communication
   * @generated
   */
  EClass getCommunication();

  /**
   * Returns the meta object for the containment reference '{@link xtext.pycom.Communication#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see xtext.pycom.Communication#getType()
   * @see #getCommunication()
   * @generated
   */
  EReference getCommunication_Type();

  /**
   * Returns the meta object for class '{@link xtext.pycom.CommunicationType <em>Communication Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Communication Type</em>'.
   * @see xtext.pycom.CommunicationType
   * @generated
   */
  EClass getCommunicationType();

  /**
   * Returns the meta object for the attribute '{@link xtext.pycom.CommunicationType#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xtext.pycom.CommunicationType#getName()
   * @see #getCommunicationType()
   * @generated
   */
  EAttribute getCommunicationType_Name();

  /**
   * Returns the meta object for the attribute '{@link xtext.pycom.CommunicationType#getSsid <em>Ssid</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ssid</em>'.
   * @see xtext.pycom.CommunicationType#getSsid()
   * @see #getCommunicationType()
   * @generated
   */
  EAttribute getCommunicationType_Ssid();

  /**
   * Returns the meta object for the attribute '{@link xtext.pycom.CommunicationType#getPassword <em>Password</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Password</em>'.
   * @see xtext.pycom.CommunicationType#getPassword()
   * @see #getCommunicationType()
   * @generated
   */
  EAttribute getCommunicationType_Password();

  /**
   * Returns the meta object for class '{@link xtext.pycom.Pin <em>Pin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pin</em>'.
   * @see xtext.pycom.Pin
   * @generated
   */
  EClass getPin();

  /**
   * Returns the meta object for the containment reference '{@link xtext.pycom.Pin#getPower <em>Power</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Power</em>'.
   * @see xtext.pycom.Pin#getPower()
   * @see #getPin()
   * @generated
   */
  EReference getPin_Power();

  /**
   * Returns the meta object for the containment reference '{@link xtext.pycom.Pin#getInput <em>Input</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Input</em>'.
   * @see xtext.pycom.Pin#getInput()
   * @see #getPin()
   * @generated
   */
  EReference getPin_Input();

  /**
   * Returns the meta object for class '{@link xtext.pycom.PinName <em>Pin Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pin Name</em>'.
   * @see xtext.pycom.PinName
   * @generated
   */
  EClass getPinName();

  /**
   * Returns the meta object for the attribute '{@link xtext.pycom.PinName#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xtext.pycom.PinName#getName()
   * @see #getPinName()
   * @generated
   */
  EAttribute getPinName_Name();

  /**
   * Returns the meta object for class '{@link xtext.pycom.Condition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condition</em>'.
   * @see xtext.pycom.Condition
   * @generated
   */
  EClass getCondition();

  /**
   * Returns the meta object for the containment reference '{@link xtext.pycom.Condition#getLogicEx <em>Logic Ex</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Logic Ex</em>'.
   * @see xtext.pycom.Condition#getLogicEx()
   * @see #getCondition()
   * @generated
   */
  EReference getCondition_LogicEx();

  /**
   * Returns the meta object for the attribute '{@link xtext.pycom.Condition#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operator</em>'.
   * @see xtext.pycom.Condition#getOperator()
   * @see #getCondition()
   * @generated
   */
  EAttribute getCondition_Operator();

  /**
   * Returns the meta object for the containment reference '{@link xtext.pycom.Condition#getNestedCondition <em>Nested Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Nested Condition</em>'.
   * @see xtext.pycom.Condition#getNestedCondition()
   * @see #getCondition()
   * @generated
   */
  EReference getCondition_NestedCondition();

  /**
   * Returns the meta object for class '{@link xtext.pycom.LogicExp <em>Logic Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Logic Exp</em>'.
   * @see xtext.pycom.LogicExp
   * @generated
   */
  EClass getLogicExp();

  /**
   * Returns the meta object for the containment reference '{@link xtext.pycom.LogicExp#getBoolVal <em>Bool Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Bool Val</em>'.
   * @see xtext.pycom.LogicExp#getBoolVal()
   * @see #getLogicExp()
   * @generated
   */
  EReference getLogicExp_BoolVal();

  /**
   * Returns the meta object for the containment reference '{@link xtext.pycom.LogicExp#getCompExp <em>Comp Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Comp Exp</em>'.
   * @see xtext.pycom.LogicExp#getCompExp()
   * @see #getLogicExp()
   * @generated
   */
  EReference getLogicExp_CompExp();

  /**
   * Returns the meta object for class '{@link xtext.pycom.Boolean <em>Boolean</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Boolean</em>'.
   * @see xtext.pycom.Boolean
   * @generated
   */
  EClass getBoolean();

  /**
   * Returns the meta object for the attribute '{@link xtext.pycom.Boolean#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see xtext.pycom.Boolean#getValue()
   * @see #getBoolean()
   * @generated
   */
  EAttribute getBoolean_Value();

  /**
   * Returns the meta object for class '{@link xtext.pycom.ComparisonExp <em>Comparison Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Comparison Exp</em>'.
   * @see xtext.pycom.ComparisonExp
   * @generated
   */
  EClass getComparisonExp();

  /**
   * Returns the meta object for the containment reference '{@link xtext.pycom.ComparisonExp#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see xtext.pycom.ComparisonExp#getLeft()
   * @see #getComparisonExp()
   * @generated
   */
  EReference getComparisonExp_Left();

  /**
   * Returns the meta object for the attribute '{@link xtext.pycom.ComparisonExp#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see xtext.pycom.ComparisonExp#getOp()
   * @see #getComparisonExp()
   * @generated
   */
  EAttribute getComparisonExp_Op();

  /**
   * Returns the meta object for the containment reference '{@link xtext.pycom.ComparisonExp#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see xtext.pycom.ComparisonExp#getRight()
   * @see #getComparisonExp()
   * @generated
   */
  EReference getComparisonExp_Right();

  /**
   * Returns the meta object for class '{@link xtext.pycom.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see xtext.pycom.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for the attribute '{@link xtext.pycom.Expression#getOutputValue <em>Output Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Output Value</em>'.
   * @see xtext.pycom.Expression#getOutputValue()
   * @see #getExpression()
   * @generated
   */
  EAttribute getExpression_OutputValue();

  /**
   * Returns the meta object for the containment reference '{@link xtext.pycom.Expression#getOutputfunction <em>Outputfunction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Outputfunction</em>'.
   * @see xtext.pycom.Expression#getOutputfunction()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Outputfunction();

  /**
   * Returns the meta object for class '{@link xtext.pycom.Function <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function</em>'.
   * @see xtext.pycom.Function
   * @generated
   */
  EClass getFunction();

  /**
   * Returns the meta object for the reference '{@link xtext.pycom.Function#getBoard <em>Board</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Board</em>'.
   * @see xtext.pycom.Function#getBoard()
   * @see #getFunction()
   * @generated
   */
  EReference getFunction_Board();

  /**
   * Returns the meta object for the reference '{@link xtext.pycom.Function#getFunctionName <em>Function Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Function Name</em>'.
   * @see xtext.pycom.Function#getFunctionName()
   * @see #getFunction()
   * @generated
   */
  EReference getFunction_FunctionName();

  /**
   * Returns the meta object for the containment reference list '{@link xtext.pycom.Function#getPins <em>Pins</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Pins</em>'.
   * @see xtext.pycom.Function#getPins()
   * @see #getFunction()
   * @generated
   */
  EReference getFunction_Pins();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  PycomFactory getPycomFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link xtext.pycom.impl.SystemImpl <em>System</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.SystemImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getSystem()
     * @generated
     */
    EClass SYSTEM = eINSTANCE.getSystem();

    /**
     * The meta object literal for the '<em><b>Libraries</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM__LIBRARIES = eINSTANCE.getSystem_Libraries();

    /**
     * The meta object literal for the '<em><b>Imports</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM__IMPORTS = eINSTANCE.getSystem_Imports();

    /**
     * The meta object literal for the '<em><b>Boards</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM__BOARDS = eINSTANCE.getSystem_Boards();

    /**
     * The meta object literal for the '<em><b>Servers</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM__SERVERS = eINSTANCE.getSystem_Servers();

    /**
     * The meta object literal for the '{@link xtext.pycom.impl.LibraryImpl <em>Library</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.LibraryImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getLibrary()
     * @generated
     */
    EClass LIBRARY = eINSTANCE.getLibrary();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LIBRARY__NAME = eINSTANCE.getLibrary_Name();

    /**
     * The meta object literal for the '<em><b>Imports</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIBRARY__IMPORTS = eINSTANCE.getLibrary_Imports();

    /**
     * The meta object literal for the '{@link xtext.pycom.impl.ImportImpl <em>Import</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.ImportImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getImport()
     * @generated
     */
    EClass IMPORT = eINSTANCE.getImport();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMPORT__NAME = eINSTANCE.getImport_Name();

    /**
     * The meta object literal for the '<em><b>Parameter</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IMPORT__PARAMETER = eINSTANCE.getImport_Parameter();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMPORT__PATH = eINSTANCE.getImport_Path();

    /**
     * The meta object literal for the '{@link xtext.pycom.impl.ParameterTypeImpl <em>Parameter Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.ParameterTypeImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getParameterType()
     * @generated
     */
    EClass PARAMETER_TYPE = eINSTANCE.getParameterType();

    /**
     * The meta object literal for the '<em><b>Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER_TYPE__NUMBER = eINSTANCE.getParameterType_Number();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER_TYPE__TEXT = eINSTANCE.getParameterType_Text();

    /**
     * The meta object literal for the '{@link xtext.pycom.impl.ServerImpl <em>Server</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.ServerImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getServer()
     * @generated
     */
    EClass SERVER = eINSTANCE.getServer();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SERVER__NAME = eINSTANCE.getServer_Name();

    /**
     * The meta object literal for the '<em><b>Conn</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SERVER__CONN = eINSTANCE.getServer_Conn();

    /**
     * The meta object literal for the '<em><b>Exps</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SERVER__EXPS = eINSTANCE.getServer_Exps();

    /**
     * The meta object literal for the '{@link xtext.pycom.impl.ConnectionImpl <em>Connection</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.ConnectionImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getConnection()
     * @generated
     */
    EClass CONNECTION = eINSTANCE.getConnection();

    /**
     * The meta object literal for the '<em><b>Host</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONNECTION__HOST = eINSTANCE.getConnection_Host();

    /**
     * The meta object literal for the '<em><b>Portnumber</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONNECTION__PORTNUMBER = eINSTANCE.getConnection_Portnumber();

    /**
     * The meta object literal for the '{@link xtext.pycom.impl.HostImpl <em>Host</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.HostImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getHost()
     * @generated
     */
    EClass HOST = eINSTANCE.getHost();

    /**
     * The meta object literal for the '<em><b>Ip Adr</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HOST__IP_ADR = eINSTANCE.getHost_IpAdr();

    /**
     * The meta object literal for the '<em><b>Website</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HOST__WEBSITE = eINSTANCE.getHost_Website();

    /**
     * The meta object literal for the '{@link xtext.pycom.impl.BoardImpl <em>Board</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.BoardImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getBoard()
     * @generated
     */
    EClass BOARD = eINSTANCE.getBoard();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOARD__NAME = eINSTANCE.getBoard_Name();

    /**
     * The meta object literal for the '<em><b>Board Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOARD__BOARD_TYPE = eINSTANCE.getBoard_BoardType();

    /**
     * The meta object literal for the '<em><b>Communication Rate</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOARD__COMMUNICATION_RATE = eINSTANCE.getBoard_CommunicationRate();

    /**
     * The meta object literal for the '<em><b>Library</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOARD__LIBRARY = eINSTANCE.getBoard_Library();

    /**
     * The meta object literal for the '<em><b>Board Members</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOARD__BOARD_MEMBERS = eINSTANCE.getBoard_BoardMembers();

    /**
     * The meta object literal for the '{@link xtext.pycom.impl.BoardMemberImpl <em>Board Member</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.BoardMemberImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getBoardMember()
     * @generated
     */
    EClass BOARD_MEMBER = eINSTANCE.getBoardMember();

    /**
     * The meta object literal for the '<em><b>Board Member</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BOARD_MEMBER__BOARD_MEMBER = eINSTANCE.getBoardMember_BoardMember();

    /**
     * The meta object literal for the '{@link xtext.pycom.impl.ConditionalActionImpl <em>Conditional Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.ConditionalActionImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getConditionalAction()
     * @generated
     */
    EClass CONDITIONAL_ACTION = eINSTANCE.getConditionalAction();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITIONAL_ACTION__TYPE = eINSTANCE.getConditionalAction_Type();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITIONAL_ACTION__CONDITION = eINSTANCE.getConditionalAction_Condition();

    /**
     * The meta object literal for the '<em><b>Exp Members</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITIONAL_ACTION__EXP_MEMBERS = eINSTANCE.getConditionalAction_ExpMembers();

    /**
     * The meta object literal for the '{@link xtext.pycom.impl.ExpMemberImpl <em>Exp Member</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.ExpMemberImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getExpMember()
     * @generated
     */
    EClass EXP_MEMBER = eINSTANCE.getExpMember();

    /**
     * The meta object literal for the '{@link xtext.pycom.impl.SensorImpl <em>Sensor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.SensorImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getSensor()
     * @generated
     */
    EClass SENSOR = eINSTANCE.getSensor();

    /**
     * The meta object literal for the '<em><b>Type Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SENSOR__TYPE_NAME = eINSTANCE.getSensor_TypeName();

    /**
     * The meta object literal for the '<em><b>Sensor Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SENSOR__SENSOR_NAME = eINSTANCE.getSensor_SensorName();

    /**
     * The meta object literal for the '<em><b>Pins</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SENSOR__PINS = eINSTANCE.getSensor_Pins();

    /**
     * The meta object literal for the '{@link xtext.pycom.impl.ActuatorImpl <em>Actuator</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.ActuatorImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getActuator()
     * @generated
     */
    EClass ACTUATOR = eINSTANCE.getActuator();

    /**
     * The meta object literal for the '<em><b>Type Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTUATOR__TYPE_NAME = eINSTANCE.getActuator_TypeName();

    /**
     * The meta object literal for the '<em><b>Actuator Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTUATOR__ACTUATOR_NAME = eINSTANCE.getActuator_ActuatorName();

    /**
     * The meta object literal for the '<em><b>Pins</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTUATOR__PINS = eINSTANCE.getActuator_Pins();

    /**
     * The meta object literal for the '{@link xtext.pycom.impl.ModuleTypeImpl <em>Module Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.ModuleTypeImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getModuleType()
     * @generated
     */
    EClass MODULE_TYPE = eINSTANCE.getModuleType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODULE_TYPE__NAME = eINSTANCE.getModuleType_Name();

    /**
     * The meta object literal for the '{@link xtext.pycom.impl.ModuleNameImpl <em>Module Name</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.ModuleNameImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getModuleName()
     * @generated
     */
    EClass MODULE_NAME = eINSTANCE.getModuleName();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODULE_NAME__NAME = eINSTANCE.getModuleName_Name();

    /**
     * The meta object literal for the '{@link xtext.pycom.impl.CommunicationImpl <em>Communication</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.CommunicationImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getCommunication()
     * @generated
     */
    EClass COMMUNICATION = eINSTANCE.getCommunication();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMMUNICATION__TYPE = eINSTANCE.getCommunication_Type();

    /**
     * The meta object literal for the '{@link xtext.pycom.impl.CommunicationTypeImpl <em>Communication Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.CommunicationTypeImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getCommunicationType()
     * @generated
     */
    EClass COMMUNICATION_TYPE = eINSTANCE.getCommunicationType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMMUNICATION_TYPE__NAME = eINSTANCE.getCommunicationType_Name();

    /**
     * The meta object literal for the '<em><b>Ssid</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMMUNICATION_TYPE__SSID = eINSTANCE.getCommunicationType_Ssid();

    /**
     * The meta object literal for the '<em><b>Password</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMMUNICATION_TYPE__PASSWORD = eINSTANCE.getCommunicationType_Password();

    /**
     * The meta object literal for the '{@link xtext.pycom.impl.PinImpl <em>Pin</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.PinImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getPin()
     * @generated
     */
    EClass PIN = eINSTANCE.getPin();

    /**
     * The meta object literal for the '<em><b>Power</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PIN__POWER = eINSTANCE.getPin_Power();

    /**
     * The meta object literal for the '<em><b>Input</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PIN__INPUT = eINSTANCE.getPin_Input();

    /**
     * The meta object literal for the '{@link xtext.pycom.impl.PinNameImpl <em>Pin Name</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.PinNameImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getPinName()
     * @generated
     */
    EClass PIN_NAME = eINSTANCE.getPinName();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PIN_NAME__NAME = eINSTANCE.getPinName_Name();

    /**
     * The meta object literal for the '{@link xtext.pycom.impl.ConditionImpl <em>Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.ConditionImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getCondition()
     * @generated
     */
    EClass CONDITION = eINSTANCE.getCondition();

    /**
     * The meta object literal for the '<em><b>Logic Ex</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITION__LOGIC_EX = eINSTANCE.getCondition_LogicEx();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION__OPERATOR = eINSTANCE.getCondition_Operator();

    /**
     * The meta object literal for the '<em><b>Nested Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITION__NESTED_CONDITION = eINSTANCE.getCondition_NestedCondition();

    /**
     * The meta object literal for the '{@link xtext.pycom.impl.LogicExpImpl <em>Logic Exp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.LogicExpImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getLogicExp()
     * @generated
     */
    EClass LOGIC_EXP = eINSTANCE.getLogicExp();

    /**
     * The meta object literal for the '<em><b>Bool Val</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOGIC_EXP__BOOL_VAL = eINSTANCE.getLogicExp_BoolVal();

    /**
     * The meta object literal for the '<em><b>Comp Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOGIC_EXP__COMP_EXP = eINSTANCE.getLogicExp_CompExp();

    /**
     * The meta object literal for the '{@link xtext.pycom.impl.BooleanImpl <em>Boolean</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.BooleanImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getBoolean()
     * @generated
     */
    EClass BOOLEAN = eINSTANCE.getBoolean();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOLEAN__VALUE = eINSTANCE.getBoolean_Value();

    /**
     * The meta object literal for the '{@link xtext.pycom.impl.ComparisonExpImpl <em>Comparison Exp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.ComparisonExpImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getComparisonExp()
     * @generated
     */
    EClass COMPARISON_EXP = eINSTANCE.getComparisonExp();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPARISON_EXP__LEFT = eINSTANCE.getComparisonExp_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPARISON_EXP__OP = eINSTANCE.getComparisonExp_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPARISON_EXP__RIGHT = eINSTANCE.getComparisonExp_Right();

    /**
     * The meta object literal for the '{@link xtext.pycom.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.ExpressionImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '<em><b>Output Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPRESSION__OUTPUT_VALUE = eINSTANCE.getExpression_OutputValue();

    /**
     * The meta object literal for the '<em><b>Outputfunction</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__OUTPUTFUNCTION = eINSTANCE.getExpression_Outputfunction();

    /**
     * The meta object literal for the '{@link xtext.pycom.impl.FunctionImpl <em>Function</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xtext.pycom.impl.FunctionImpl
     * @see xtext.pycom.impl.PycomPackageImpl#getFunction()
     * @generated
     */
    EClass FUNCTION = eINSTANCE.getFunction();

    /**
     * The meta object literal for the '<em><b>Board</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION__BOARD = eINSTANCE.getFunction_Board();

    /**
     * The meta object literal for the '<em><b>Function Name</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION__FUNCTION_NAME = eINSTANCE.getFunction_FunctionName();

    /**
     * The meta object literal for the '<em><b>Pins</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION__PINS = eINSTANCE.getFunction_Pins();

  }

} //PycomPackage
