/**
 * generated by Xtext 2.16.0
 */
package xtext.pycom;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sensor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xtext.pycom.Sensor#getTypeName <em>Type Name</em>}</li>
 *   <li>{@link xtext.pycom.Sensor#getSensorName <em>Sensor Name</em>}</li>
 *   <li>{@link xtext.pycom.Sensor#getPins <em>Pins</em>}</li>
 * </ul>
 *
 * @see xtext.pycom.PycomPackage#getSensor()
 * @model
 * @generated
 */
public interface Sensor extends EObject
{
  /**
   * Returns the value of the '<em><b>Type Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type Name</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Name</em>' containment reference.
   * @see #setTypeName(ModuleType)
   * @see xtext.pycom.PycomPackage#getSensor_TypeName()
   * @model containment="true"
   * @generated
   */
  ModuleType getTypeName();

  /**
   * Sets the value of the '{@link xtext.pycom.Sensor#getTypeName <em>Type Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type Name</em>' containment reference.
   * @see #getTypeName()
   * @generated
   */
  void setTypeName(ModuleType value);

  /**
   * Returns the value of the '<em><b>Sensor Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sensor Name</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sensor Name</em>' containment reference.
   * @see #setSensorName(ModuleName)
   * @see xtext.pycom.PycomPackage#getSensor_SensorName()
   * @model containment="true"
   * @generated
   */
  ModuleName getSensorName();

  /**
   * Sets the value of the '{@link xtext.pycom.Sensor#getSensorName <em>Sensor Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sensor Name</em>' containment reference.
   * @see #getSensorName()
   * @generated
   */
  void setSensorName(ModuleName value);

  /**
   * Returns the value of the '<em><b>Pins</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pins</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pins</em>' containment reference.
   * @see #setPins(Pin)
   * @see xtext.pycom.PycomPackage#getSensor_Pins()
   * @model containment="true"
   * @generated
   */
  Pin getPins();

  /**
   * Sets the value of the '{@link xtext.pycom.Sensor#getPins <em>Pins</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pins</em>' containment reference.
   * @see #getPins()
   * @generated
   */
  void setPins(Pin value);

} // Sensor
