/*
 * generated by Xtext 2.16.0
 */
package xtext.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class PycomGrammarAccess extends AbstractGrammarElementFinder {
	
	public class SystemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.Pycom.System");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cLibrariesAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cLibrariesLibraryParserRuleCall_0_0 = (RuleCall)cLibrariesAssignment_0.eContents().get(0);
		private final Assignment cImportsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cImportsImportParserRuleCall_1_0 = (RuleCall)cImportsAssignment_1.eContents().get(0);
		private final Assignment cBoardsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cBoardsBoardParserRuleCall_2_0 = (RuleCall)cBoardsAssignment_2.eContents().get(0);
		private final Assignment cServersAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cServersServerParserRuleCall_3_0 = (RuleCall)cServersAssignment_3.eContents().get(0);
		
		//System:
		//	libraries+=Library* imports+=Import* boards+=Board* servers+=Server*;
		@Override public ParserRule getRule() { return rule; }
		
		//libraries+=Library* imports+=Import* boards+=Board* servers+=Server*
		public Group getGroup() { return cGroup; }
		
		//libraries+=Library*
		public Assignment getLibrariesAssignment_0() { return cLibrariesAssignment_0; }
		
		//Library
		public RuleCall getLibrariesLibraryParserRuleCall_0_0() { return cLibrariesLibraryParserRuleCall_0_0; }
		
		//imports+=Import*
		public Assignment getImportsAssignment_1() { return cImportsAssignment_1; }
		
		//Import
		public RuleCall getImportsImportParserRuleCall_1_0() { return cImportsImportParserRuleCall_1_0; }
		
		//boards+=Board*
		public Assignment getBoardsAssignment_2() { return cBoardsAssignment_2; }
		
		//Board
		public RuleCall getBoardsBoardParserRuleCall_2_0() { return cBoardsBoardParserRuleCall_2_0; }
		
		//servers+=Server*
		public Assignment getServersAssignment_3() { return cServersAssignment_3; }
		
		//Server
		public RuleCall getServersServerParserRuleCall_3_0() { return cServersServerParserRuleCall_3_0; }
	}
	public class LibraryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.Pycom.Library");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLibraryKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cImportsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cImportsImportParserRuleCall_3_0 = (RuleCall)cImportsAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Library:
		//	'Library' name=ID '{' imports+=Import* '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Library' name=ID '{' imports+=Import* '}'
		public Group getGroup() { return cGroup; }
		
		//'Library'
		public Keyword getLibraryKeyword_0() { return cLibraryKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//imports+=Import*
		public Assignment getImportsAssignment_3() { return cImportsAssignment_3; }
		
		//Import
		public RuleCall getImportsImportParserRuleCall_3_0() { return cImportsImportParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class ImportElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.Pycom.Import");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cImportKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cParameterAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cParameterParameterTypeParserRuleCall_3_0 = (RuleCall)cParameterAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCommaKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cParameterAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cParameterParameterTypeParserRuleCall_4_1_0 = (RuleCall)cParameterAssignment_4_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cFromKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cPathAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cPathSTRINGTerminalRuleCall_7_0 = (RuleCall)cPathAssignment_7.eContents().get(0);
		
		//Import:
		//	'import' name=ID '(' parameter+=ParameterType? (',' parameter+=ParameterType)* ')' 'from' path=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//'import' name=ID '(' parameter+=ParameterType? (',' parameter+=ParameterType)* ')' 'from' path=STRING
		public Group getGroup() { return cGroup; }
		
		//'import'
		public Keyword getImportKeyword_0() { return cImportKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }
		
		//parameter+=ParameterType?
		public Assignment getParameterAssignment_3() { return cParameterAssignment_3; }
		
		//ParameterType
		public RuleCall getParameterParameterTypeParserRuleCall_3_0() { return cParameterParameterTypeParserRuleCall_3_0; }
		
		//(',' parameter+=ParameterType)*
		public Group getGroup_4() { return cGroup_4; }
		
		//','
		public Keyword getCommaKeyword_4_0() { return cCommaKeyword_4_0; }
		
		//parameter+=ParameterType
		public Assignment getParameterAssignment_4_1() { return cParameterAssignment_4_1; }
		
		//ParameterType
		public RuleCall getParameterParameterTypeParserRuleCall_4_1_0() { return cParameterParameterTypeParserRuleCall_4_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5() { return cRightParenthesisKeyword_5; }
		
		//'from'
		public Keyword getFromKeyword_6() { return cFromKeyword_6; }
		
		//path=STRING
		public Assignment getPathAssignment_7() { return cPathAssignment_7; }
		
		//STRING
		public RuleCall getPathSTRINGTerminalRuleCall_7_0() { return cPathSTRINGTerminalRuleCall_7_0; }
	}
	public class ParameterTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.Pycom.ParameterType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cNumberAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cNumberINTTerminalRuleCall_0_0 = (RuleCall)cNumberAssignment_0.eContents().get(0);
		private final Assignment cTextAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cTextSTRINGTerminalRuleCall_1_0 = (RuleCall)cTextAssignment_1.eContents().get(0);
		
		//ParameterType:
		//	number=INT | text=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//number=INT | text=STRING
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//number=INT
		public Assignment getNumberAssignment_0() { return cNumberAssignment_0; }
		
		//INT
		public RuleCall getNumberINTTerminalRuleCall_0_0() { return cNumberINTTerminalRuleCall_0_0; }
		
		//text=STRING
		public Assignment getTextAssignment_1() { return cTextAssignment_1; }
		
		//STRING
		public RuleCall getTextSTRINGTerminalRuleCall_1_0() { return cTextSTRINGTerminalRuleCall_1_0; }
	}
	public class ServerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.Pycom.Server");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cServerKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cConnAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cConnConnectionParserRuleCall_3_0 = (RuleCall)cConnAssignment_3.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cExpsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cExpsConditionalActionParserRuleCall_6_0 = (RuleCall)cExpsAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Server:
		//	'Server' name=ID '(' conn=Connection ')' '{' exps+=ConditionalAction* '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Server' name=ID '(' conn=Connection ')' '{' exps+=ConditionalAction* '}'
		public Group getGroup() { return cGroup; }
		
		//'Server'
		public Keyword getServerKeyword_0() { return cServerKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }
		
		//conn=Connection
		public Assignment getConnAssignment_3() { return cConnAssignment_3; }
		
		//Connection
		public RuleCall getConnConnectionParserRuleCall_3_0() { return cConnConnectionParserRuleCall_3_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }
		
		//exps+=ConditionalAction*
		public Assignment getExpsAssignment_6() { return cExpsAssignment_6; }
		
		//ConditionalAction
		public RuleCall getExpsConditionalActionParserRuleCall_6_0() { return cExpsConditionalActionParserRuleCall_6_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class ConnectionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.Pycom.Connection");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cHostAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cHostHostParserRuleCall_0_0 = (RuleCall)cHostAssignment_0.eContents().get(0);
		private final Keyword cCommaKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cPortnumberAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cPortnumberINTTerminalRuleCall_2_0 = (RuleCall)cPortnumberAssignment_2.eContents().get(0);
		
		//Connection:
		//	host=Host ',' portnumber=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//host=Host ',' portnumber=INT
		public Group getGroup() { return cGroup; }
		
		//host=Host
		public Assignment getHostAssignment_0() { return cHostAssignment_0; }
		
		//Host
		public RuleCall getHostHostParserRuleCall_0_0() { return cHostHostParserRuleCall_0_0; }
		
		//','
		public Keyword getCommaKeyword_1() { return cCommaKeyword_1; }
		
		//portnumber=INT
		public Assignment getPortnumberAssignment_2() { return cPortnumberAssignment_2; }
		
		//INT
		public RuleCall getPortnumberINTTerminalRuleCall_2_0() { return cPortnumberINTTerminalRuleCall_2_0; }
	}
	public class HostElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.Pycom.Host");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cIpAdrAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cIpAdrIpaddressParserRuleCall_0_0 = (RuleCall)cIpAdrAssignment_0.eContents().get(0);
		private final Assignment cWebsiteAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cWebsiteSTRINGTerminalRuleCall_1_0 = (RuleCall)cWebsiteAssignment_1.eContents().get(0);
		
		//Host:
		//	ipAdr=Ipaddress | website=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//ipAdr=Ipaddress | website=STRING
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ipAdr=Ipaddress
		public Assignment getIpAdrAssignment_0() { return cIpAdrAssignment_0; }
		
		//Ipaddress
		public RuleCall getIpAdrIpaddressParserRuleCall_0_0() { return cIpAdrIpaddressParserRuleCall_0_0; }
		
		//website=STRING
		public Assignment getWebsiteAssignment_1() { return cWebsiteAssignment_1; }
		
		//STRING
		public RuleCall getWebsiteSTRINGTerminalRuleCall_1_0() { return cWebsiteSTRINGTerminalRuleCall_1_0; }
	}
	public class IpaddressElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.Pycom.Ipaddress");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Keyword cFullStopKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final Keyword cFullStopKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final RuleCall cINTTerminalRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		private final Keyword cFullStopKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final RuleCall cINTTerminalRuleCall_6 = (RuleCall)cGroup.eContents().get(6);
		
		//Ipaddress:
		//	INT '.' INT '.' INT '.' INT;
		@Override public ParserRule getRule() { return rule; }
		
		//INT '.' INT '.' INT '.' INT
		public Group getGroup() { return cGroup; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_0() { return cINTTerminalRuleCall_0; }
		
		//'.'
		public Keyword getFullStopKeyword_1() { return cFullStopKeyword_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_2() { return cINTTerminalRuleCall_2; }
		
		//'.'
		public Keyword getFullStopKeyword_3() { return cFullStopKeyword_3; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_4() { return cINTTerminalRuleCall_4; }
		
		//'.'
		public Keyword getFullStopKeyword_5() { return cFullStopKeyword_5; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_6() { return cINTTerminalRuleCall_6; }
	}
	public class BoardElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.Pycom.Board");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBoardKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cBoardTypeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cBoardTypeIDTerminalRuleCall_3_0 = (RuleCall)cBoardTypeAssignment_3.eContents().get(0);
		private final Keyword cCommaKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cCommunicationRateAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cCommunicationRateINTTerminalRuleCall_5_0 = (RuleCall)cCommunicationRateAssignment_5.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cUsesKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cLibraryAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final CrossReference cLibraryLibraryCrossReference_7_1_0 = (CrossReference)cLibraryAssignment_7_1.eContents().get(0);
		private final RuleCall cLibraryLibraryIDTerminalRuleCall_7_1_0_1 = (RuleCall)cLibraryLibraryCrossReference_7_1_0.eContents().get(1);
		private final Group cGroup_7_2 = (Group)cGroup_7.eContents().get(2);
		private final Keyword cCommaKeyword_7_2_0 = (Keyword)cGroup_7_2.eContents().get(0);
		private final Assignment cLibraryAssignment_7_2_1 = (Assignment)cGroup_7_2.eContents().get(1);
		private final CrossReference cLibraryLibraryCrossReference_7_2_1_0 = (CrossReference)cLibraryAssignment_7_2_1.eContents().get(0);
		private final RuleCall cLibraryLibraryIDTerminalRuleCall_7_2_1_0_1 = (RuleCall)cLibraryLibraryCrossReference_7_2_1_0.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cBoardMembersAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cBoardMembersBoardMemberParserRuleCall_9_0 = (RuleCall)cBoardMembersAssignment_9.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//Board:
		//	'Board' name=ID '(' boardType=ID ',' communicationRate=INT ')' ('uses' library+=[Library]? (','
		//	library+=[Library])*)? '{' boardMembers+=BoardMember* '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Board' name=ID '(' boardType=ID ',' communicationRate=INT ')' ('uses' library+=[Library]? (',' library+=[Library])*)?
		//'{' boardMembers+=BoardMember* '}'
		public Group getGroup() { return cGroup; }
		
		//'Board'
		public Keyword getBoardKeyword_0() { return cBoardKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }
		
		//boardType=ID
		public Assignment getBoardTypeAssignment_3() { return cBoardTypeAssignment_3; }
		
		//ID
		public RuleCall getBoardTypeIDTerminalRuleCall_3_0() { return cBoardTypeIDTerminalRuleCall_3_0; }
		
		//','
		public Keyword getCommaKeyword_4() { return cCommaKeyword_4; }
		
		//communicationRate=INT
		public Assignment getCommunicationRateAssignment_5() { return cCommunicationRateAssignment_5; }
		
		//INT
		public RuleCall getCommunicationRateINTTerminalRuleCall_5_0() { return cCommunicationRateINTTerminalRuleCall_5_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_6() { return cRightParenthesisKeyword_6; }
		
		//('uses' library+=[Library]? (',' library+=[Library])*)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'uses'
		public Keyword getUsesKeyword_7_0() { return cUsesKeyword_7_0; }
		
		//library+=[Library]?
		public Assignment getLibraryAssignment_7_1() { return cLibraryAssignment_7_1; }
		
		//[Library]
		public CrossReference getLibraryLibraryCrossReference_7_1_0() { return cLibraryLibraryCrossReference_7_1_0; }
		
		//ID
		public RuleCall getLibraryLibraryIDTerminalRuleCall_7_1_0_1() { return cLibraryLibraryIDTerminalRuleCall_7_1_0_1; }
		
		//(',' library+=[Library])*
		public Group getGroup_7_2() { return cGroup_7_2; }
		
		//','
		public Keyword getCommaKeyword_7_2_0() { return cCommaKeyword_7_2_0; }
		
		//library+=[Library]
		public Assignment getLibraryAssignment_7_2_1() { return cLibraryAssignment_7_2_1; }
		
		//[Library]
		public CrossReference getLibraryLibraryCrossReference_7_2_1_0() { return cLibraryLibraryCrossReference_7_2_1_0; }
		
		//ID
		public RuleCall getLibraryLibraryIDTerminalRuleCall_7_2_1_0_1() { return cLibraryLibraryIDTerminalRuleCall_7_2_1_0_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_8() { return cLeftCurlyBracketKeyword_8; }
		
		//boardMembers+=BoardMember*
		public Assignment getBoardMembersAssignment_9() { return cBoardMembersAssignment_9; }
		
		//BoardMember
		public RuleCall getBoardMembersBoardMemberParserRuleCall_9_0() { return cBoardMembersBoardMemberParserRuleCall_9_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}
	public class BoardMemberElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.Pycom.BoardMember");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cBoardMemberAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cBoardMemberSensorParserRuleCall_0_0 = (RuleCall)cBoardMemberAssignment_0.eContents().get(0);
		private final RuleCall cActuatorParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cCommunicationParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//BoardMember:
		//	boardMember=Sensor | Actuator | Communication;
		@Override public ParserRule getRule() { return rule; }
		
		//boardMember=Sensor | Actuator | Communication
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//boardMember=Sensor
		public Assignment getBoardMemberAssignment_0() { return cBoardMemberAssignment_0; }
		
		//Sensor
		public RuleCall getBoardMemberSensorParserRuleCall_0_0() { return cBoardMemberSensorParserRuleCall_0_0; }
		
		//Actuator
		public RuleCall getActuatorParserRuleCall_1() { return cActuatorParserRuleCall_1; }
		
		//Communication
		public RuleCall getCommunicationParserRuleCall_2() { return cCommunicationParserRuleCall_2; }
	}
	public class ConditionalActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.Pycom.ConditionalAction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTypeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cTypeIfKeyword_0_0 = (Keyword)cTypeAssignment_0.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cConditionAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cConditionConditionParserRuleCall_2_0 = (RuleCall)cConditionAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cExpMembersAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cExpMembersExpMemberParserRuleCall_5_0 = (RuleCall)cExpMembersAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//ConditionalAction:
		//	type='if' '(' condition=Condition ')' '{' ExpMembers+=ExpMember* '}';
		@Override public ParserRule getRule() { return rule; }
		
		//type='if' '(' condition=Condition ')' '{' ExpMembers+=ExpMember* '}'
		public Group getGroup() { return cGroup; }
		
		//type='if'
		public Assignment getTypeAssignment_0() { return cTypeAssignment_0; }
		
		//'if'
		public Keyword getTypeIfKeyword_0_0() { return cTypeIfKeyword_0_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//condition=Condition
		public Assignment getConditionAssignment_2() { return cConditionAssignment_2; }
		
		//Condition
		public RuleCall getConditionConditionParserRuleCall_2_0() { return cConditionConditionParserRuleCall_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }
		
		//ExpMembers+=ExpMember*
		public Assignment getExpMembersAssignment_5() { return cExpMembersAssignment_5; }
		
		//ExpMember
		public RuleCall getExpMembersExpMemberParserRuleCall_5_0() { return cExpMembersExpMemberParserRuleCall_5_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class ExpMemberElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.Pycom.ExpMember");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cFunctionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cConditionalActionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//ExpMember:
		//	Function | ConditionalAction;
		@Override public ParserRule getRule() { return rule; }
		
		//Function | ConditionalAction
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Function
		public RuleCall getFunctionParserRuleCall_0() { return cFunctionParserRuleCall_0; }
		
		//ConditionalAction
		public RuleCall getConditionalActionParserRuleCall_1() { return cConditionalActionParserRuleCall_1; }
	}
	public class SensorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.Pycom.Sensor");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSensorKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTypeNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTypeNameModuleTypeParserRuleCall_1_0 = (RuleCall)cTypeNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cSensorNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cSensorNameModuleNameParserRuleCall_3_0 = (RuleCall)cSensorNameAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cLeftParenthesisKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cPinsAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cPinsPinParserRuleCall_4_1_0 = (RuleCall)cPinsAssignment_4_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4_2 = (Keyword)cGroup_4.eContents().get(2);
		
		//Sensor:
		//	'Sensor' typeName=ModuleType ':' sensorName=ModuleName ('(' pins=Pin ')')?;
		@Override public ParserRule getRule() { return rule; }
		
		//'Sensor' typeName=ModuleType ':' sensorName=ModuleName ('(' pins=Pin ')')?
		public Group getGroup() { return cGroup; }
		
		//'Sensor'
		public Keyword getSensorKeyword_0() { return cSensorKeyword_0; }
		
		//typeName=ModuleType
		public Assignment getTypeNameAssignment_1() { return cTypeNameAssignment_1; }
		
		//ModuleType
		public RuleCall getTypeNameModuleTypeParserRuleCall_1_0() { return cTypeNameModuleTypeParserRuleCall_1_0; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//sensorName=ModuleName
		public Assignment getSensorNameAssignment_3() { return cSensorNameAssignment_3; }
		
		//ModuleName
		public RuleCall getSensorNameModuleNameParserRuleCall_3_0() { return cSensorNameModuleNameParserRuleCall_3_0; }
		
		//('(' pins=Pin ')')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_0() { return cLeftParenthesisKeyword_4_0; }
		
		//pins=Pin
		public Assignment getPinsAssignment_4_1() { return cPinsAssignment_4_1; }
		
		//Pin
		public RuleCall getPinsPinParserRuleCall_4_1_0() { return cPinsPinParserRuleCall_4_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_2() { return cRightParenthesisKeyword_4_2; }
	}
	public class ActuatorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.Pycom.Actuator");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cActuatorKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTypeNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTypeNameModuleTypeParserRuleCall_1_0 = (RuleCall)cTypeNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cActuatorNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cActuatorNameModuleNameParserRuleCall_3_0 = (RuleCall)cActuatorNameAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cLeftParenthesisKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cPinsAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cPinsPinParserRuleCall_4_1_0 = (RuleCall)cPinsAssignment_4_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4_2 = (Keyword)cGroup_4.eContents().get(2);
		
		//Actuator:
		//	'Actuator' typeName=ModuleType ':' actuatorName=ModuleName ('(' pins=Pin ')')?;
		@Override public ParserRule getRule() { return rule; }
		
		//'Actuator' typeName=ModuleType ':' actuatorName=ModuleName ('(' pins=Pin ')')?
		public Group getGroup() { return cGroup; }
		
		//'Actuator'
		public Keyword getActuatorKeyword_0() { return cActuatorKeyword_0; }
		
		//typeName=ModuleType
		public Assignment getTypeNameAssignment_1() { return cTypeNameAssignment_1; }
		
		//ModuleType
		public RuleCall getTypeNameModuleTypeParserRuleCall_1_0() { return cTypeNameModuleTypeParserRuleCall_1_0; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//actuatorName=ModuleName
		public Assignment getActuatorNameAssignment_3() { return cActuatorNameAssignment_3; }
		
		//ModuleName
		public RuleCall getActuatorNameModuleNameParserRuleCall_3_0() { return cActuatorNameModuleNameParserRuleCall_3_0; }
		
		//('(' pins=Pin ')')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_0() { return cLeftParenthesisKeyword_4_0; }
		
		//pins=Pin
		public Assignment getPinsAssignment_4_1() { return cPinsAssignment_4_1; }
		
		//Pin
		public RuleCall getPinsPinParserRuleCall_4_1_0() { return cPinsPinParserRuleCall_4_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_2() { return cRightParenthesisKeyword_4_2; }
	}
	public class ModuleTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.Pycom.ModuleType");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//ModuleType:
		//	name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID
		public Assignment getNameAssignment() { return cNameAssignment; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0() { return cNameIDTerminalRuleCall_0; }
	}
	public class ModuleNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.Pycom.ModuleName");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//ModuleName:
		//	name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID
		public Assignment getNameAssignment() { return cNameAssignment; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0() { return cNameIDTerminalRuleCall_0; }
	}
	public class CommunicationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.Pycom.Communication");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCommunicationKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTypeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTypeCommunicationTypeParserRuleCall_2_0 = (RuleCall)cTypeAssignment_2.eContents().get(0);
		
		//Communication:
		//	'Communication' ':' type=CommunicationType;
		@Override public ParserRule getRule() { return rule; }
		
		//'Communication' ':' type=CommunicationType
		public Group getGroup() { return cGroup; }
		
		//'Communication'
		public Keyword getCommunicationKeyword_0() { return cCommunicationKeyword_0; }
		
		//':'
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//type=CommunicationType
		public Assignment getTypeAssignment_2() { return cTypeAssignment_2; }
		
		//CommunicationType
		public RuleCall getTypeCommunicationTypeParserRuleCall_2_0() { return cTypeCommunicationTypeParserRuleCall_2_0; }
	}
	public class CommunicationTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.Pycom.CommunicationType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Assignment cNameAssignment_0_0 = (Assignment)cGroup_0.eContents().get(0);
		private final Keyword cNameWiFiKeyword_0_0_0 = (Keyword)cNameAssignment_0_0.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Assignment cSsidAssignment_0_2 = (Assignment)cGroup_0.eContents().get(2);
		private final RuleCall cSsidSTRINGTerminalRuleCall_0_2_0 = (RuleCall)cSsidAssignment_0_2.eContents().get(0);
		private final Keyword cCommaKeyword_0_3 = (Keyword)cGroup_0.eContents().get(3);
		private final Assignment cPasswordAssignment_0_4 = (Assignment)cGroup_0.eContents().get(4);
		private final RuleCall cPasswordSTRINGTerminalRuleCall_0_4_0 = (RuleCall)cPasswordAssignment_0_4.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_0_5 = (Keyword)cGroup_0.eContents().get(5);
		private final Assignment cNameAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final Keyword cNameBluetoothKeyword_1_0 = (Keyword)cNameAssignment_1.eContents().get(0);
		private final Assignment cNameAssignment_2 = (Assignment)cAlternatives.eContents().get(2);
		private final Keyword cNameSigFoxKeyword_2_0 = (Keyword)cNameAssignment_2.eContents().get(0);
		
		//CommunicationType:
		//	name='WiFi' '(' ssid=STRING ',' password=STRING ')' | name='Bluetooth' | name='SigFox';
		@Override public ParserRule getRule() { return rule; }
		
		//name='WiFi' '(' ssid=STRING ',' password=STRING ')' | name='Bluetooth' | name='SigFox'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//name='WiFi' '(' ssid=STRING ',' password=STRING ')'
		public Group getGroup_0() { return cGroup_0; }
		
		//name='WiFi'
		public Assignment getNameAssignment_0_0() { return cNameAssignment_0_0; }
		
		//'WiFi'
		public Keyword getNameWiFiKeyword_0_0_0() { return cNameWiFiKeyword_0_0_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_0_1() { return cLeftParenthesisKeyword_0_1; }
		
		//ssid=STRING
		public Assignment getSsidAssignment_0_2() { return cSsidAssignment_0_2; }
		
		//STRING
		public RuleCall getSsidSTRINGTerminalRuleCall_0_2_0() { return cSsidSTRINGTerminalRuleCall_0_2_0; }
		
		//','
		public Keyword getCommaKeyword_0_3() { return cCommaKeyword_0_3; }
		
		//password=STRING
		public Assignment getPasswordAssignment_0_4() { return cPasswordAssignment_0_4; }
		
		//STRING
		public RuleCall getPasswordSTRINGTerminalRuleCall_0_4_0() { return cPasswordSTRINGTerminalRuleCall_0_4_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_0_5() { return cRightParenthesisKeyword_0_5; }
		
		//name='Bluetooth'
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//'Bluetooth'
		public Keyword getNameBluetoothKeyword_1_0() { return cNameBluetoothKeyword_1_0; }
		
		//name='SigFox'
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//'SigFox'
		public Keyword getNameSigFoxKeyword_2_0() { return cNameSigFoxKeyword_2_0; }
	}
	public class PinElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.Pycom.Pin");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cPowerAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cPowerPinNameParserRuleCall_0_0 = (RuleCall)cPowerAssignment_0.eContents().get(0);
		private final Keyword cCommaKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cInputAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cInputPinNameParserRuleCall_2_0 = (RuleCall)cInputAssignment_2.eContents().get(0);
		
		//Pin:
		//	power=PinName ',' input=PinName;
		@Override public ParserRule getRule() { return rule; }
		
		//power=PinName ',' input=PinName
		public Group getGroup() { return cGroup; }
		
		//power=PinName
		public Assignment getPowerAssignment_0() { return cPowerAssignment_0; }
		
		//PinName
		public RuleCall getPowerPinNameParserRuleCall_0_0() { return cPowerPinNameParserRuleCall_0_0; }
		
		//','
		public Keyword getCommaKeyword_1() { return cCommaKeyword_1; }
		
		//input=PinName
		public Assignment getInputAssignment_2() { return cInputAssignment_2; }
		
		//PinName
		public RuleCall getInputPinNameParserRuleCall_2_0() { return cInputPinNameParserRuleCall_2_0; }
	}
	public class PinNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.Pycom.PinName");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//PinName:
		//	name=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//name=STRING
		public Assignment getNameAssignment() { return cNameAssignment; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_0() { return cNameSTRINGTerminalRuleCall_0; }
	}
	public class ConditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.Pycom.Condition");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cLogicExAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cLogicExLogicExpParserRuleCall_0_0 = (RuleCall)cLogicExAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Assignment cLogicExAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final RuleCall cLogicExLogicExpParserRuleCall_1_0_0 = (RuleCall)cLogicExAssignment_1_0.eContents().get(0);
		private final Assignment cOperatorAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final Keyword cOperatorAmpersandAmpersandKeyword_1_1_0 = (Keyword)cOperatorAssignment_1_1.eContents().get(0);
		private final Assignment cNestedConditionAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cNestedConditionConditionParserRuleCall_1_2_0 = (RuleCall)cNestedConditionAssignment_1_2.eContents().get(0);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Assignment cLogicExAssignment_2_0 = (Assignment)cGroup_2.eContents().get(0);
		private final RuleCall cLogicExLogicExpParserRuleCall_2_0_0 = (RuleCall)cLogicExAssignment_2_0.eContents().get(0);
		private final Assignment cOperatorAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final Keyword cOperatorVerticalLineVerticalLineKeyword_2_1_0 = (Keyword)cOperatorAssignment_2_1.eContents().get(0);
		private final Assignment cNestedConditionAssignment_2_2 = (Assignment)cGroup_2.eContents().get(2);
		private final RuleCall cNestedConditionConditionParserRuleCall_2_2_0 = (RuleCall)cNestedConditionAssignment_2_2.eContents().get(0);
		
		//Condition:
		//	logicEx=LogicExp | logicEx=LogicExp operator='&&' nestedCondition=Condition | logicEx=LogicExp operator='||'
		//	nestedCondition=Condition;
		@Override public ParserRule getRule() { return rule; }
		
		//logicEx=LogicExp | logicEx=LogicExp operator='&&' nestedCondition=Condition | logicEx=LogicExp operator='||'
		//nestedCondition=Condition
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//logicEx=LogicExp
		public Assignment getLogicExAssignment_0() { return cLogicExAssignment_0; }
		
		//LogicExp
		public RuleCall getLogicExLogicExpParserRuleCall_0_0() { return cLogicExLogicExpParserRuleCall_0_0; }
		
		//logicEx=LogicExp operator='&&' nestedCondition=Condition
		public Group getGroup_1() { return cGroup_1; }
		
		//logicEx=LogicExp
		public Assignment getLogicExAssignment_1_0() { return cLogicExAssignment_1_0; }
		
		//LogicExp
		public RuleCall getLogicExLogicExpParserRuleCall_1_0_0() { return cLogicExLogicExpParserRuleCall_1_0_0; }
		
		//operator='&&'
		public Assignment getOperatorAssignment_1_1() { return cOperatorAssignment_1_1; }
		
		//'&&'
		public Keyword getOperatorAmpersandAmpersandKeyword_1_1_0() { return cOperatorAmpersandAmpersandKeyword_1_1_0; }
		
		//nestedCondition=Condition
		public Assignment getNestedConditionAssignment_1_2() { return cNestedConditionAssignment_1_2; }
		
		//Condition
		public RuleCall getNestedConditionConditionParserRuleCall_1_2_0() { return cNestedConditionConditionParserRuleCall_1_2_0; }
		
		//logicEx=LogicExp operator='||' nestedCondition=Condition
		public Group getGroup_2() { return cGroup_2; }
		
		//logicEx=LogicExp
		public Assignment getLogicExAssignment_2_0() { return cLogicExAssignment_2_0; }
		
		//LogicExp
		public RuleCall getLogicExLogicExpParserRuleCall_2_0_0() { return cLogicExLogicExpParserRuleCall_2_0_0; }
		
		//operator='||'
		public Assignment getOperatorAssignment_2_1() { return cOperatorAssignment_2_1; }
		
		//'||'
		public Keyword getOperatorVerticalLineVerticalLineKeyword_2_1_0() { return cOperatorVerticalLineVerticalLineKeyword_2_1_0; }
		
		//nestedCondition=Condition
		public Assignment getNestedConditionAssignment_2_2() { return cNestedConditionAssignment_2_2; }
		
		//Condition
		public RuleCall getNestedConditionConditionParserRuleCall_2_2_0() { return cNestedConditionConditionParserRuleCall_2_2_0; }
	}
	public class LogicExpElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.Pycom.LogicExp");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cBoolValAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cBoolValBooleanParserRuleCall_0_0 = (RuleCall)cBoolValAssignment_0.eContents().get(0);
		private final Assignment cCompExpAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cCompExpComparisonExpParserRuleCall_1_0 = (RuleCall)cCompExpAssignment_1.eContents().get(0);
		
		//LogicExp:
		//	boolVal=Boolean | compExp=ComparisonExp;
		@Override public ParserRule getRule() { return rule; }
		
		//boolVal=Boolean | compExp=ComparisonExp
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//boolVal=Boolean
		public Assignment getBoolValAssignment_0() { return cBoolValAssignment_0; }
		
		//Boolean
		public RuleCall getBoolValBooleanParserRuleCall_0_0() { return cBoolValBooleanParserRuleCall_0_0; }
		
		//compExp=ComparisonExp
		public Assignment getCompExpAssignment_1() { return cCompExpAssignment_1; }
		
		//ComparisonExp
		public RuleCall getCompExpComparisonExpParserRuleCall_1_0() { return cCompExpComparisonExpParserRuleCall_1_0; }
	}
	public class BooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.Pycom.Boolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cValueAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final Keyword cValueTrueKeyword_0_0 = (Keyword)cValueAssignment_0.eContents().get(0);
		private final Assignment cValueAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final Keyword cValueFalseKeyword_1_0 = (Keyword)cValueAssignment_1.eContents().get(0);
		
		//Boolean:
		//	value='true' | value='false';
		@Override public ParserRule getRule() { return rule; }
		
		//value='true' | value='false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//value='true'
		public Assignment getValueAssignment_0() { return cValueAssignment_0; }
		
		//'true'
		public Keyword getValueTrueKeyword_0_0() { return cValueTrueKeyword_0_0; }
		
		//value='false'
		public Assignment getValueAssignment_1() { return cValueAssignment_1; }
		
		//'false'
		public Keyword getValueFalseKeyword_1_0() { return cValueFalseKeyword_1_0; }
	}
	public class ComparisonExpElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.Pycom.ComparisonExp");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cLeftAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cLeftExpressionParserRuleCall_0_0 = (RuleCall)cLeftAssignment_0.eContents().get(0);
		private final Assignment cOpAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cOpOperatorParserRuleCall_1_0 = (RuleCall)cOpAssignment_1.eContents().get(0);
		private final Assignment cRightAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cRightExpressionParserRuleCall_2_0 = (RuleCall)cRightAssignment_2.eContents().get(0);
		
		//ComparisonExp:
		//	left=Expression op=Operator right=Expression;
		@Override public ParserRule getRule() { return rule; }
		
		//left=Expression op=Operator right=Expression
		public Group getGroup() { return cGroup; }
		
		//left=Expression
		public Assignment getLeftAssignment_0() { return cLeftAssignment_0; }
		
		//Expression
		public RuleCall getLeftExpressionParserRuleCall_0_0() { return cLeftExpressionParserRuleCall_0_0; }
		
		//op=Operator
		public Assignment getOpAssignment_1() { return cOpAssignment_1; }
		
		//Operator
		public RuleCall getOpOperatorParserRuleCall_1_0() { return cOpOperatorParserRuleCall_1_0; }
		
		//right=Expression
		public Assignment getRightAssignment_2() { return cRightAssignment_2; }
		
		//Expression
		public RuleCall getRightExpressionParserRuleCall_2_0() { return cRightExpressionParserRuleCall_2_0; }
	}
	public class ExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.Pycom.Expression");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cOutputValueAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cOutputValueINTTerminalRuleCall_0_0 = (RuleCall)cOutputValueAssignment_0.eContents().get(0);
		private final Assignment cOutputfunctionAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cOutputfunctionFunctionParserRuleCall_1_0 = (RuleCall)cOutputfunctionAssignment_1.eContents().get(0);
		
		//Expression:
		//	outputValue=INT | outputfunction=Function;
		@Override public ParserRule getRule() { return rule; }
		
		//outputValue=INT | outputfunction=Function
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//outputValue=INT
		public Assignment getOutputValueAssignment_0() { return cOutputValueAssignment_0; }
		
		//INT
		public RuleCall getOutputValueINTTerminalRuleCall_0_0() { return cOutputValueINTTerminalRuleCall_0_0; }
		
		//outputfunction=Function
		public Assignment getOutputfunctionAssignment_1() { return cOutputfunctionAssignment_1; }
		
		//Function
		public RuleCall getOutputfunctionFunctionParserRuleCall_1_0() { return cOutputfunctionFunctionParserRuleCall_1_0; }
	}
	public class OperatorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.Pycom.Operator");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cLessThanSignKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cLessThanSignEqualsSignKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cEqualsSignEqualsSignKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cGreaterThanSignEqualsSignKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		private final Keyword cGreaterThanSignKeyword_4 = (Keyword)cAlternatives.eContents().get(4);
		private final Keyword cExclamationMarkEqualsSignKeyword_5 = (Keyword)cAlternatives.eContents().get(5);
		
		//Operator:
		//	'<' | '<=' | '==' | '>=' | '>' | '!=';
		@Override public ParserRule getRule() { return rule; }
		
		//'<' | '<=' | '==' | '>=' | '>' | '!='
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'<'
		public Keyword getLessThanSignKeyword_0() { return cLessThanSignKeyword_0; }
		
		//'<='
		public Keyword getLessThanSignEqualsSignKeyword_1() { return cLessThanSignEqualsSignKeyword_1; }
		
		//'=='
		public Keyword getEqualsSignEqualsSignKeyword_2() { return cEqualsSignEqualsSignKeyword_2; }
		
		//'>='
		public Keyword getGreaterThanSignEqualsSignKeyword_3() { return cGreaterThanSignEqualsSignKeyword_3; }
		
		//'>'
		public Keyword getGreaterThanSignKeyword_4() { return cGreaterThanSignKeyword_4; }
		
		//'!='
		public Keyword getExclamationMarkEqualsSignKeyword_5() { return cExclamationMarkEqualsSignKeyword_5; }
	}
	public class FunctionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xtext.Pycom.Function");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cBoardAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cBoardBoardCrossReference_0_0 = (CrossReference)cBoardAssignment_0.eContents().get(0);
		private final RuleCall cBoardBoardIDTerminalRuleCall_0_0_1 = (RuleCall)cBoardBoardCrossReference_0_0.eContents().get(1);
		private final Keyword cFullStopKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cFunctionNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cFunctionNameImportCrossReference_2_0 = (CrossReference)cFunctionNameAssignment_2.eContents().get(0);
		private final RuleCall cFunctionNameImportIDTerminalRuleCall_2_0_1 = (RuleCall)cFunctionNameImportCrossReference_2_0.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cPinsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cPinsPinParserRuleCall_4_0 = (RuleCall)cPinsAssignment_4.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Function:
		//	board=[Board] '.' functionName=[Import] '(' pins+=Pin? ')';
		@Override public ParserRule getRule() { return rule; }
		
		//board=[Board] '.' functionName=[Import] '(' pins+=Pin? ')'
		public Group getGroup() { return cGroup; }
		
		//board=[Board]
		public Assignment getBoardAssignment_0() { return cBoardAssignment_0; }
		
		//[Board]
		public CrossReference getBoardBoardCrossReference_0_0() { return cBoardBoardCrossReference_0_0; }
		
		//ID
		public RuleCall getBoardBoardIDTerminalRuleCall_0_0_1() { return cBoardBoardIDTerminalRuleCall_0_0_1; }
		
		//'.'
		public Keyword getFullStopKeyword_1() { return cFullStopKeyword_1; }
		
		//functionName=[Import]
		public Assignment getFunctionNameAssignment_2() { return cFunctionNameAssignment_2; }
		
		//[Import]
		public CrossReference getFunctionNameImportCrossReference_2_0() { return cFunctionNameImportCrossReference_2_0; }
		
		//ID
		public RuleCall getFunctionNameImportIDTerminalRuleCall_2_0_1() { return cFunctionNameImportIDTerminalRuleCall_2_0_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_3() { return cLeftParenthesisKeyword_3; }
		
		//pins+=Pin?
		public Assignment getPinsAssignment_4() { return cPinsAssignment_4; }
		
		//Pin
		public RuleCall getPinsPinParserRuleCall_4_0() { return cPinsPinParserRuleCall_4_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5() { return cRightParenthesisKeyword_5; }
	}
	
	
	private final SystemElements pSystem;
	private final LibraryElements pLibrary;
	private final ImportElements pImport;
	private final ParameterTypeElements pParameterType;
	private final ServerElements pServer;
	private final ConnectionElements pConnection;
	private final HostElements pHost;
	private final IpaddressElements pIpaddress;
	private final BoardElements pBoard;
	private final BoardMemberElements pBoardMember;
	private final ConditionalActionElements pConditionalAction;
	private final ExpMemberElements pExpMember;
	private final SensorElements pSensor;
	private final ActuatorElements pActuator;
	private final ModuleTypeElements pModuleType;
	private final ModuleNameElements pModuleName;
	private final CommunicationElements pCommunication;
	private final CommunicationTypeElements pCommunicationType;
	private final PinElements pPin;
	private final PinNameElements pPinName;
	private final ConditionElements pCondition;
	private final LogicExpElements pLogicExp;
	private final BooleanElements pBoolean;
	private final ComparisonExpElements pComparisonExp;
	private final ExpressionElements pExpression;
	private final OperatorElements pOperator;
	private final FunctionElements pFunction;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public PycomGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pSystem = new SystemElements();
		this.pLibrary = new LibraryElements();
		this.pImport = new ImportElements();
		this.pParameterType = new ParameterTypeElements();
		this.pServer = new ServerElements();
		this.pConnection = new ConnectionElements();
		this.pHost = new HostElements();
		this.pIpaddress = new IpaddressElements();
		this.pBoard = new BoardElements();
		this.pBoardMember = new BoardMemberElements();
		this.pConditionalAction = new ConditionalActionElements();
		this.pExpMember = new ExpMemberElements();
		this.pSensor = new SensorElements();
		this.pActuator = new ActuatorElements();
		this.pModuleType = new ModuleTypeElements();
		this.pModuleName = new ModuleNameElements();
		this.pCommunication = new CommunicationElements();
		this.pCommunicationType = new CommunicationTypeElements();
		this.pPin = new PinElements();
		this.pPinName = new PinNameElements();
		this.pCondition = new ConditionElements();
		this.pLogicExp = new LogicExpElements();
		this.pBoolean = new BooleanElements();
		this.pComparisonExp = new ComparisonExpElements();
		this.pExpression = new ExpressionElements();
		this.pOperator = new OperatorElements();
		this.pFunction = new FunctionElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("xtext.Pycom".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//System:
	//	libraries+=Library* imports+=Import* boards+=Board* servers+=Server*;
	public SystemElements getSystemAccess() {
		return pSystem;
	}
	
	public ParserRule getSystemRule() {
		return getSystemAccess().getRule();
	}
	
	//Library:
	//	'Library' name=ID '{' imports+=Import* '}';
	public LibraryElements getLibraryAccess() {
		return pLibrary;
	}
	
	public ParserRule getLibraryRule() {
		return getLibraryAccess().getRule();
	}
	
	//Import:
	//	'import' name=ID '(' parameter+=ParameterType? (',' parameter+=ParameterType)* ')' 'from' path=STRING;
	public ImportElements getImportAccess() {
		return pImport;
	}
	
	public ParserRule getImportRule() {
		return getImportAccess().getRule();
	}
	
	//ParameterType:
	//	number=INT | text=STRING;
	public ParameterTypeElements getParameterTypeAccess() {
		return pParameterType;
	}
	
	public ParserRule getParameterTypeRule() {
		return getParameterTypeAccess().getRule();
	}
	
	//Server:
	//	'Server' name=ID '(' conn=Connection ')' '{' exps+=ConditionalAction* '}';
	public ServerElements getServerAccess() {
		return pServer;
	}
	
	public ParserRule getServerRule() {
		return getServerAccess().getRule();
	}
	
	//Connection:
	//	host=Host ',' portnumber=INT;
	public ConnectionElements getConnectionAccess() {
		return pConnection;
	}
	
	public ParserRule getConnectionRule() {
		return getConnectionAccess().getRule();
	}
	
	//Host:
	//	ipAdr=Ipaddress | website=STRING;
	public HostElements getHostAccess() {
		return pHost;
	}
	
	public ParserRule getHostRule() {
		return getHostAccess().getRule();
	}
	
	//Ipaddress:
	//	INT '.' INT '.' INT '.' INT;
	public IpaddressElements getIpaddressAccess() {
		return pIpaddress;
	}
	
	public ParserRule getIpaddressRule() {
		return getIpaddressAccess().getRule();
	}
	
	//Board:
	//	'Board' name=ID '(' boardType=ID ',' communicationRate=INT ')' ('uses' library+=[Library]? (','
	//	library+=[Library])*)? '{' boardMembers+=BoardMember* '}';
	public BoardElements getBoardAccess() {
		return pBoard;
	}
	
	public ParserRule getBoardRule() {
		return getBoardAccess().getRule();
	}
	
	//BoardMember:
	//	boardMember=Sensor | Actuator | Communication;
	public BoardMemberElements getBoardMemberAccess() {
		return pBoardMember;
	}
	
	public ParserRule getBoardMemberRule() {
		return getBoardMemberAccess().getRule();
	}
	
	//ConditionalAction:
	//	type='if' '(' condition=Condition ')' '{' ExpMembers+=ExpMember* '}';
	public ConditionalActionElements getConditionalActionAccess() {
		return pConditionalAction;
	}
	
	public ParserRule getConditionalActionRule() {
		return getConditionalActionAccess().getRule();
	}
	
	//ExpMember:
	//	Function | ConditionalAction;
	public ExpMemberElements getExpMemberAccess() {
		return pExpMember;
	}
	
	public ParserRule getExpMemberRule() {
		return getExpMemberAccess().getRule();
	}
	
	//Sensor:
	//	'Sensor' typeName=ModuleType ':' sensorName=ModuleName ('(' pins=Pin ')')?;
	public SensorElements getSensorAccess() {
		return pSensor;
	}
	
	public ParserRule getSensorRule() {
		return getSensorAccess().getRule();
	}
	
	//Actuator:
	//	'Actuator' typeName=ModuleType ':' actuatorName=ModuleName ('(' pins=Pin ')')?;
	public ActuatorElements getActuatorAccess() {
		return pActuator;
	}
	
	public ParserRule getActuatorRule() {
		return getActuatorAccess().getRule();
	}
	
	//ModuleType:
	//	name=ID;
	public ModuleTypeElements getModuleTypeAccess() {
		return pModuleType;
	}
	
	public ParserRule getModuleTypeRule() {
		return getModuleTypeAccess().getRule();
	}
	
	//ModuleName:
	//	name=ID;
	public ModuleNameElements getModuleNameAccess() {
		return pModuleName;
	}
	
	public ParserRule getModuleNameRule() {
		return getModuleNameAccess().getRule();
	}
	
	//Communication:
	//	'Communication' ':' type=CommunicationType;
	public CommunicationElements getCommunicationAccess() {
		return pCommunication;
	}
	
	public ParserRule getCommunicationRule() {
		return getCommunicationAccess().getRule();
	}
	
	//CommunicationType:
	//	name='WiFi' '(' ssid=STRING ',' password=STRING ')' | name='Bluetooth' | name='SigFox';
	public CommunicationTypeElements getCommunicationTypeAccess() {
		return pCommunicationType;
	}
	
	public ParserRule getCommunicationTypeRule() {
		return getCommunicationTypeAccess().getRule();
	}
	
	//Pin:
	//	power=PinName ',' input=PinName;
	public PinElements getPinAccess() {
		return pPin;
	}
	
	public ParserRule getPinRule() {
		return getPinAccess().getRule();
	}
	
	//PinName:
	//	name=STRING;
	public PinNameElements getPinNameAccess() {
		return pPinName;
	}
	
	public ParserRule getPinNameRule() {
		return getPinNameAccess().getRule();
	}
	
	//Condition:
	//	logicEx=LogicExp | logicEx=LogicExp operator='&&' nestedCondition=Condition | logicEx=LogicExp operator='||'
	//	nestedCondition=Condition;
	public ConditionElements getConditionAccess() {
		return pCondition;
	}
	
	public ParserRule getConditionRule() {
		return getConditionAccess().getRule();
	}
	
	//LogicExp:
	//	boolVal=Boolean | compExp=ComparisonExp;
	public LogicExpElements getLogicExpAccess() {
		return pLogicExp;
	}
	
	public ParserRule getLogicExpRule() {
		return getLogicExpAccess().getRule();
	}
	
	//Boolean:
	//	value='true' | value='false';
	public BooleanElements getBooleanAccess() {
		return pBoolean;
	}
	
	public ParserRule getBooleanRule() {
		return getBooleanAccess().getRule();
	}
	
	//ComparisonExp:
	//	left=Expression op=Operator right=Expression;
	public ComparisonExpElements getComparisonExpAccess() {
		return pComparisonExp;
	}
	
	public ParserRule getComparisonExpRule() {
		return getComparisonExpAccess().getRule();
	}
	
	//Expression:
	//	outputValue=INT | outputfunction=Function;
	public ExpressionElements getExpressionAccess() {
		return pExpression;
	}
	
	public ParserRule getExpressionRule() {
		return getExpressionAccess().getRule();
	}
	
	//Operator:
	//	'<' | '<=' | '==' | '>=' | '>' | '!=';
	public OperatorElements getOperatorAccess() {
		return pOperator;
	}
	
	public ParserRule getOperatorRule() {
		return getOperatorAccess().getRule();
	}
	
	//Function:
	//	board=[Board] '.' functionName=[Import] '(' pins+=Pin? ')';
	public FunctionElements getFunctionAccess() {
		return pFunction;
	}
	
	public ParserRule getFunctionRule() {
		return getFunctionAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
